/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as ApiBlobsCardIdAttachmentIdRouteImport } from './routes/api/blobs.$cardId.$attachmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/cards/$cardId',
  path: '/cards/$cardId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobsCardIdAttachmentIdRoute =
  ApiBlobsCardIdAttachmentIdRouteImport.update({
    id: '/api/blobs/$cardId/$attachmentId',
    path: '/api/blobs/$cardId/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/api/blobs/$cardId/$attachmentId': typeof ApiBlobsCardIdAttachmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/api/blobs/$cardId/$attachmentId': typeof ApiBlobsCardIdAttachmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/api/blobs/$cardId/$attachmentId': typeof ApiBlobsCardIdAttachmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intake'
    | '/cards/$cardId'
    | '/api/blobs/$cardId/$attachmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/intake' | '/cards/$cardId' | '/api/blobs/$cardId/$attachmentId'
  id:
    | '__root__'
    | '/'
    | '/intake'
    | '/cards/$cardId'
    | '/api/blobs/$cardId/$attachmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntakeRoute: typeof IntakeRoute
  CardsCardIdRoute: typeof CardsCardIdRoute
  ApiBlobsCardIdAttachmentIdRoute: typeof ApiBlobsCardIdAttachmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/cards/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blobs/$cardId/$attachmentId': {
      id: '/api/blobs/$cardId/$attachmentId'
      path: '/api/blobs/$cardId/$attachmentId'
      fullPath: '/api/blobs/$cardId/$attachmentId'
      preLoaderRoute: typeof ApiBlobsCardIdAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntakeRoute: IntakeRoute,
  CardsCardIdRoute: CardsCardIdRoute,
  ApiBlobsCardIdAttachmentIdRoute: ApiBlobsCardIdAttachmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
