/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as SpecimensSpecimenIdRouteImport } from './routes/specimens.$specimenId'
import { Route as TestbedVantaRouteImport } from './routes/testbed.vanta'
import { Route as ApiBlobsSpecimenIdAttachmentIdRouteImport } from './routes/api/blobs.$specimenId.$attachmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecimensSpecimenIdRoute = SpecimensSpecimenIdRouteImport.update({
  id: '/specimens/$specimenId',
  path: '/specimens/$specimenId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestbedVantaRoute = TestbedVantaRouteImport.update({
  id: '/testbed/vanta',
  path: '/testbed/vanta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlobsSpecimenIdAttachmentIdRoute =
  ApiBlobsSpecimenIdAttachmentIdRouteImport.update({
    id: '/api/blobs/$specimenId/$attachmentId',
    path: '/api/blobs/$specimenId/$attachmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/specimens/$specimenId': typeof SpecimensSpecimenIdRoute
  '/testbed/vanta': typeof TestbedVantaRoute
  '/api/blobs/$specimenId/$attachmentId': typeof ApiBlobsSpecimenIdAttachmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/specimens/$specimenId': typeof SpecimensSpecimenIdRoute
  '/testbed/vanta': typeof TestbedVantaRoute
  '/api/blobs/$specimenId/$attachmentId': typeof ApiBlobsSpecimenIdAttachmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/intake': typeof IntakeRoute
  '/specimens/$specimenId': typeof SpecimensSpecimenIdRoute
  '/testbed/vanta': typeof TestbedVantaRoute
  '/api/blobs/$specimenId/$attachmentId': typeof ApiBlobsSpecimenIdAttachmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/intake'
    | '/specimens/$specimenId'
    | '/testbed/vanta'
    | '/api/blobs/$specimenId/$attachmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/intake'
    | '/specimens/$specimenId'
    | '/testbed/vanta'
    | '/api/blobs/$specimenId/$attachmentId'
  id:
    | '__root__'
    | '/'
    | '/intake'
    | '/specimens/$specimenId'
    | '/testbed/vanta'
    | '/api/blobs/$specimenId/$attachmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IntakeRoute: typeof IntakeRoute
  SpecimensSpecimenIdRoute: typeof SpecimensSpecimenIdRoute
  TestbedVantaRoute: typeof TestbedVantaRoute
  ApiBlobsSpecimenIdAttachmentIdRoute: typeof ApiBlobsSpecimenIdAttachmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specimens/$specimenId': {
      id: '/specimens/$specimenId'
      path: '/specimens/$specimenId'
      fullPath: '/specimens/$specimenId'
      preLoaderRoute: typeof SpecimensSpecimenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testbed/vanta': {
      id: '/testbed/vanta'
      path: '/testbed/vanta'
      fullPath: '/testbed/vanta'
      preLoaderRoute: typeof TestbedVantaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blobs/$specimenId/$attachmentId': {
      id: '/api/blobs/$specimenId/$attachmentId'
      path: '/api/blobs/$specimenId/$attachmentId'
      fullPath: '/api/blobs/$specimenId/$attachmentId'
      preLoaderRoute: typeof ApiBlobsSpecimenIdAttachmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IntakeRoute: IntakeRoute,
  SpecimensSpecimenIdRoute: SpecimensSpecimenIdRoute,
  TestbedVantaRoute: TestbedVantaRoute,
  ApiBlobsSpecimenIdAttachmentIdRoute: ApiBlobsSpecimenIdAttachmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
