/**
 * @tmnl/pct/frames — explicit frame projection contracts and compilers.
 *
 * Frames are coherent read models assembled from pure source streams. PCT owns
 * their declarative contracts; runtimes compile and materialize them into
 * LNK frame streams and/or Timescale hypertables.
 */

export {
  FrameAssemblySpec,
  FrameColumnRole,
  FrameMaterializationMode,
  FrameOutputSpec,
  FrameProjectionSpec,
  FrameSourceBinding,
  FrameSqlColumn,
  FrameTimeoutPolicy,
  ProjectionDdlStatement,
  ProjectionPlan,
  SqlColumnType,
  type FrameAssemblySpec as FrameAssemblySpecType,
  type FrameColumnRole as FrameColumnRoleType,
  type FrameMaterializationMode as FrameMaterializationModeType,
  type FrameOutputSpec as FrameOutputSpecType,
  type FrameProjectionSpec as FrameProjectionSpecType,
  type FrameSourceBinding as FrameSourceBindingType,
  type FrameSqlColumn as FrameSqlColumnType,
  type FrameTimeoutPolicy as FrameTimeoutPolicyType,
  type ProjectionDdlStatement as ProjectionDdlStatementType,
  type ProjectionPlan as ProjectionPlanType,
  type SqlColumnType as SqlColumnTypeType,
} from "./FrameProjectionSpec.js"

export {
  FrameProjectionCompileError,
  compileTimescaleProjection,
  compileTimescaleProjectionUnsafe,
} from "./TimescaleProjectionCompiler.js"

export {
  FrameAssemblyState,
  FrameCompleteness,
  FramePart,
  FramePartProvenance,
  MaterializedFrame,
  ProjectionDeadLetter,
  ProjectionOutputKind,
  ProjectionOutputReceipt,
  ProjectionRunMode,
  ProjectionSourceMessage,
  ProjectionTickResult,
  ProjectionTimeoutOutcome,
  ProjectionWorkerConfig,
  ProjectionWorkerRunSummary,
  ProjectionWorkerSnapshot,
  ProjectionWorkerStatus,
  type FrameAssemblyState as FrameAssemblyStateType,
  type FrameCompleteness as FrameCompletenessType,
  type FramePart as FramePartType,
  type FramePartProvenance as FramePartProvenanceType,
  type MaterializedFrame as MaterializedFrameType,
  type ProjectionDeadLetter as ProjectionDeadLetterType,
  type ProjectionOutputKind as ProjectionOutputKindType,
  type ProjectionOutputReceipt as ProjectionOutputReceiptType,
  type ProjectionRunMode as ProjectionRunModeType,
  type ProjectionSourceMessage as ProjectionSourceMessageType,
  type ProjectionTickResult as ProjectionTickResultType,
  type ProjectionTimeoutOutcome as ProjectionTimeoutOutcomeType,
  type ProjectionWorkerConfig as ProjectionWorkerConfigType,
  type ProjectionWorkerRunSummary as ProjectionWorkerRunSummaryType,
  type ProjectionWorkerSnapshot as ProjectionWorkerSnapshotType,
  type ProjectionWorkerStatus as ProjectionWorkerStatusType,
} from "./ProjectionWorker.js"

export {
  DEFAULT_PROJECTION_SCHEDULER_TUNING,
  ProjectionAdmissionController,
  ProjectionAdmissionDecision,
  ProjectionAdmissionStatus,
  ProjectionLanePressure,
  ProjectionParkingReason,
  ProjectionParkingRecord,
  ProjectionRetryPolicy,
  ProjectionSchedulerPressureSnapshot,
  ProjectionSchedulerTuning,
  ProjectionWorkItem,
  ProjectionWorkLease,
  ProjectionWorkLane,
  ProjectionWorkLedger,
  makeProjectionWorkItem,
  projectionAdmissionControllerLayerMemory,
  projectionSchedulerTuningLayer,
  projectionSchedulingMemoryLayer,
  projectionWorkLedgerLayerMemory,
  type DrainReadyProjectionWorkOptions,
  type MakeProjectionWorkItemOptions,
  type ProjectionAdmissionControllerShape,
  type ProjectionAdmissionDecision as ProjectionAdmissionDecisionType,
  type ProjectionAdmissionRunResult,
  type ProjectionAdmissionStatus as ProjectionAdmissionStatusType,
  type ProjectionLanePressure as ProjectionLanePressureType,
  type ProjectionParkingReason as ProjectionParkingReasonType,
  type ProjectionParkingRecord as ProjectionParkingRecordType,
  type ProjectionRetryPolicy as ProjectionRetryPolicyType,
  type ProjectionSchedulerPressureSnapshot as ProjectionSchedulerPressureSnapshotType,
  type ProjectionSchedulerTuningShape,
  type ProjectionWorkItem as ProjectionWorkItemType,
  type ProjectionWorkLease as ProjectionWorkLeaseType,
  type ProjectionWorkLane as ProjectionWorkLaneType,
  type ProjectionWorkLedgerShape,
} from "./ProjectionScheduling.js"

export {
  ProjectionWorkerAlreadyRunning,
  ProjectionWorkerNotFound,
  ProjectionWorkerRunner,
  ProjectionWorkerScheduler,
  noopProjectionWorkerRunnerLayer,
  projectionWorkerSchedulerLayer,
  projectionWorkerSchedulerLayerWithPorts,
  type ProjectionWorkerRunnerShape,
  type ProjectionWorkerSchedulerError,
  type ProjectionWorkerSchedulerShape,
} from "./ProjectionScheduler.js"

export {
  ProjectionNotFound,
  ProjectionRegistry,
  ProjectionRegistryEntry,
  ProjectionRegistryFilter,
  ProjectionRegistryStatus,
  projectionRegistryLayerMemory,
  type ProjectionRegistryEntry as ProjectionRegistryEntryType,
  type ProjectionRegistryFilter as ProjectionRegistryFilterType,
  type ProjectionRegistryShape,
  type ProjectionRegistryStatus as ProjectionRegistryStatusType,
  type RegisterProjectionOptions,
} from "./ProjectionRegistry.js"

export {
  ProjectionWorkerControl,
  ProjectionWorkerControlFailure,
  ProjectionWorkerNatsHost,
  makeProjectionWorkerNatsEndpoints,
  makeProjectionWorkerNatsHost,
  mapProjectionWorkerNatsError,
  projectionWorkerNatsHostLayer,
  type ProjectionWorkerControlShape,
  type ProjectionWorkerNatsHostShape,
} from "./ProjectionWorkerNatsHost.js"

export {
  DEFAULT_PROJECTION_WORKER_NATS_OPTIONS,
  ProjectionPlanRequest,
  ProjectionPlanResponse,
  ProjectionRunOnceRequest,
  ProjectionRunOnceResponse,
  ProjectionStartRequest,
  ProjectionStartResponse,
  ProjectionStatusRequest,
  ProjectionStatusResponse,
  ProjectionStopRequest,
  ProjectionStopResponse,
  ProjectionTailRequest,
  ProjectionTailResponse,
  ProjectionWorkerNatsOperation,
  ProjectionWorkerSelector,
  ProjectionWorkerStartMode,
  projectionWorkerNatsOperations,
  resolveProjectionWorkerNatsOptions,
  type ProjectionPlanRequest as ProjectionPlanRequestType,
  type ProjectionPlanResponse as ProjectionPlanResponseType,
  type ProjectionRunOnceRequest as ProjectionRunOnceRequestType,
  type ProjectionRunOnceResponse as ProjectionRunOnceResponseType,
  type ProjectionStartRequest as ProjectionStartRequestType,
  type ProjectionStartResponse as ProjectionStartResponseType,
  type ProjectionStatusRequest as ProjectionStatusRequestType,
  type ProjectionStatusResponse as ProjectionStatusResponseType,
  type ProjectionStopRequest as ProjectionStopRequestType,
  type ProjectionStopResponse as ProjectionStopResponseType,
  type ProjectionTailRequest as ProjectionTailRequestType,
  type ProjectionTailResponse as ProjectionTailResponseType,
  type ProjectionWorkerNatsOperation as ProjectionWorkerNatsOperationType,
  type ProjectionWorkerNatsOptions,
  type ProjectionWorkerSelector as ProjectionWorkerSelectorType,
  type ProjectionWorkerStartMode as ProjectionWorkerStartModeType,
  type ResolvedProjectionWorkerNatsOptions,
} from "./NatsMicroContracts.js"
