/**
 * @tmnl/pct/frames — explicit frame projection contracts and compilers.
 *
 * Frames are coherent read models assembled from pure source streams. PCT owns
 * their declarative contracts; runtimes compile and materialize them into
 * LNK frame streams and/or Timescale hypertables.
 */

export {
  FrameAssemblySpec,
  FrameColumnRole,
  FrameMaterializationMode,
  FrameOutputSpec,
  FrameProjectionSpec,
  FrameSourceBinding,
  FrameSqlColumn,
  FrameTimeoutPolicy,
  ProjectionDdlStatement,
  ProjectionPlan,
  SqlColumnType,
  type FrameAssemblySpec as FrameAssemblySpecType,
  type FrameColumnRole as FrameColumnRoleType,
  type FrameMaterializationMode as FrameMaterializationModeType,
  type FrameOutputSpec as FrameOutputSpecType,
  type FrameProjectionSpec as FrameProjectionSpecType,
  type FrameSourceBinding as FrameSourceBindingType,
  type FrameSqlColumn as FrameSqlColumnType,
  type FrameTimeoutPolicy as FrameTimeoutPolicyType,
  type ProjectionDdlStatement as ProjectionDdlStatementType,
  type ProjectionPlan as ProjectionPlanType,
  type SqlColumnType as SqlColumnTypeType,
} from "./FrameProjectionSpec.js"

export {
  ProjectionAssemblyError,
  ProjectionFrameBucket,
  ProjectionPartLedgerDecision,
  ProjectionPartLedgerEntry,
  ProjectionPartLedgerState,
  ProjectionSourceOffsetKey,
  calculateCompleteness,
  calculateFrameBucket,
  deterministicFrameId,
  emptyProjectionPartLedgerState,
  frameTimeoutOutcome,
  ledgerDecisionForPart,
  mergeFramePart,
  recordLedgerDecision,
  sourceMessageToFramePart,
  sourceOffsetKey,
  type MergeFramePartResult,
  type ProjectionFrameBucket as ProjectionFrameBucketType,
  type ProjectionPartLedgerDecision as ProjectionPartLedgerDecisionType,
  type ProjectionPartLedgerEntry as ProjectionPartLedgerEntryType,
  type ProjectionPartLedgerState as ProjectionPartLedgerStateType,
  type ProjectionSourceOffsetKey as ProjectionSourceOffsetKeyType,
} from "./ProjectionAssembly.js"

export {
  FrameProjectionCompileError,
  compileTimescaleProjection,
  compileTimescaleProjectionUnsafe,
} from "./TimescaleProjectionCompiler.js"

export {
  FrameAssemblyState,
  FrameCompleteness,
  FramePart,
  FramePartProvenance,
  MaterializedFrame,
  ProjectionDeadLetter,
  ProjectionOutputKind,
  ProjectionOutputReceipt,
  ProjectionRunMode,
  ProjectionSourceMessage,
  ProjectionTickResult,
  ProjectionTimeoutOutcome,
  ProjectionWorkerConfig,
  ProjectionWorkerRunSummary,
  ProjectionWorkerSnapshot,
  ProjectionWorkerStatus,
  type FrameAssemblyState as FrameAssemblyStateType,
  type FrameCompleteness as FrameCompletenessType,
  type FramePart as FramePartType,
  type FramePartProvenance as FramePartProvenanceType,
  type MaterializedFrame as MaterializedFrameType,
  type ProjectionDeadLetter as ProjectionDeadLetterType,
  type ProjectionOutputKind as ProjectionOutputKindType,
  type ProjectionOutputReceipt as ProjectionOutputReceiptType,
  type ProjectionRunMode as ProjectionRunModeType,
  type ProjectionSourceMessage as ProjectionSourceMessageType,
  type ProjectionTickResult as ProjectionTickResultType,
  type ProjectionTimeoutOutcome as ProjectionTimeoutOutcomeType,
  type ProjectionWorkerConfig as ProjectionWorkerConfigType,
  type ProjectionWorkerRunSummary as ProjectionWorkerRunSummaryType,
  type ProjectionWorkerSnapshot as ProjectionWorkerSnapshotType,
  type ProjectionWorkerStatus as ProjectionWorkerStatusType,
} from "./ProjectionWorker.js"

export {
  DEFAULT_PROJECTION_SCHEDULER_TUNING,
  ProjectionAdmissionController,
  ProjectionAdmissionDecision,
  ProjectionAdmissionStatus,
  ProjectionLanePressure,
  ProjectionParkingReason,
  ProjectionParkingRecord,
  ProjectionRetryPolicy,
  ProjectionSchedulerPressureSnapshot,
  ProjectionSchedulerTuning,
  ProjectionWorkItem,
  ProjectionWorkLease,
  ProjectionWorkLane,
  ProjectionWorkLedger,
  makeProjectionWorkItem,
  projectionAdmissionControllerLayerMemory,
  projectionSchedulerTuningLayer,
  projectionSchedulingMemoryLayer,
  projectionWorkLedgerLayerMemory,
  type DrainReadyProjectionWorkOptions,
  type MakeProjectionWorkItemOptions,
  type ProjectionAdmissionControllerShape,
  type ProjectionAdmissionDecision as ProjectionAdmissionDecisionType,
  type ProjectionAdmissionRunResult,
  type ProjectionAdmissionStatus as ProjectionAdmissionStatusType,
  type ProjectionLanePressure as ProjectionLanePressureType,
  type ProjectionParkingReason as ProjectionParkingReasonType,
  type ProjectionParkingRecord as ProjectionParkingRecordType,
  type ProjectionRetryPolicy as ProjectionRetryPolicyType,
  type ProjectionSchedulerPressureSnapshot as ProjectionSchedulerPressureSnapshotType,
  type ProjectionSchedulerTuningShape,
  type ProjectionWorkItem as ProjectionWorkItemType,
  type ProjectionWorkLease as ProjectionWorkLeaseType,
  type ProjectionWorkLane as ProjectionWorkLaneType,
  type ProjectionWorkLedgerShape,
} from "./ProjectionScheduling.js"

export {
  ProjectionCheckpointCommit,
  ProjectionCheckpointError,
  ProjectionCheckpointRecord,
  ProjectionCheckpointStore,
  ProjectionDurableIngestOutcome,
  ProjectionDurableStateError,
  ProjectionDurableStateStore,
  ProjectionDurableWorkLane,
  ProjectionFrameEmissionState,
  ProjectionIngestPartInput,
  ProjectionIngestPartResult,
  ProjectionLease,
  ProjectionLeaseAcquire,
  ProjectionLeaseDenied,
  ProjectionLeaseLost,
  ProjectionLeaseRelease,
  ProjectionLeaseRenew,
  ProjectionLeaseStore,
  ProjectionOutboxError,
  ProjectionOutboxFailed,
  ProjectionOutboxPendingRequest,
  ProjectionOutboxPublished,
  ProjectionOutboxRecord,
  ProjectionOutboxStatus,
  ProjectionOutputOutbox,
  ProjectionSourceBindingKey,
  ProjectionTimeoutSweepInput,
  ProjectionTimeoutSweepOutcome,
  ProjectionTimeoutSweepResult,
  projectionDurableRuntimeMemoryLayer,
  projectionDurableRuntimeMemoryLayerWithFaults,
  type ProjectionCheckpointCommit as ProjectionCheckpointCommitType,
  type ProjectionCheckpointRecord as ProjectionCheckpointRecordType,
  type ProjectionCheckpointStoreShape,
  type ProjectionDurableIngestOutcome as ProjectionDurableIngestOutcomeType,
  type ProjectionDurableRuntimeMemoryOptions,
  type ProjectionDurableStateStoreShape,
  type ProjectionDurableWorkLane as ProjectionDurableWorkLaneType,
  type ProjectionFrameEmissionState as ProjectionFrameEmissionStateType,
  type ProjectionIngestPartInput as ProjectionIngestPartInputType,
  type ProjectionIngestPartResult as ProjectionIngestPartResultType,
  type ProjectionLease as ProjectionLeaseType,
  type ProjectionLeaseAcquire as ProjectionLeaseAcquireType,
  type ProjectionLeaseRelease as ProjectionLeaseReleaseType,
  type ProjectionLeaseRenew as ProjectionLeaseRenewType,
  type ProjectionLeaseStoreShape,
  type ProjectionOutboxFailed as ProjectionOutboxFailedType,
  type ProjectionOutboxPendingRequest as ProjectionOutboxPendingRequestType,
  type ProjectionOutboxPublished as ProjectionOutboxPublishedType,
  type ProjectionOutboxRecord as ProjectionOutboxRecordType,
  type ProjectionOutboxStatus as ProjectionOutboxStatusType,
  type ProjectionOutputOutboxShape,
  type ProjectionSourceBindingKey as ProjectionSourceBindingKeyType,
  type ProjectionTimeoutSweepInput as ProjectionTimeoutSweepInputType,
  type ProjectionTimeoutSweepOutcome as ProjectionTimeoutSweepOutcomeType,
  type ProjectionTimeoutSweepResult as ProjectionTimeoutSweepResultType,
} from "./ProjectionDurableRuntime.js"

export {
  ProjectionOutboxPublishAttempt,
  ProjectionOutboxPublishRequest,
  ProjectionOutboxPublishSummary,
  ProjectionOutboxPublisher,
  projectionOutboxPublisherLayer,
  type ProjectionOutboxPublishAttempt as ProjectionOutboxPublishAttemptType,
  type ProjectionOutboxPublishRequest as ProjectionOutboxPublishRequestType,
  type ProjectionOutboxPublishSummary as ProjectionOutboxPublishSummaryType,
  type ProjectionOutboxPublisherShape,
} from "./ProjectionOutboxPublisher.js"

export {
  ProjectionFrameStreamPublisherService,
  ProjectionLnkFramePublishError,
  ProjectionLnkSourceReadError,
  projectionFrameStreamPublisherLayerLnkWire,
  projectionLnkSourceReadErrorToRuntimeError,
  projectionOutboxRecordToRuntimeError,
  projectionSourceReaderLayerLnkWire,
  type ProjectionFrameStreamPublisherServiceShape,
  type ProjectionFrameStreamPublisherShape,
  type ProjectionLnkSourceReaderOptions,
} from "./ProjectionLnkAdapters.js"

export {
  FrameStreamWriter,
  ProjectionRuntimeError,
  ProjectionSourceReader,
  TimescaleFrameWriter,
  frameStreamWriterLayerMemory,
  noopFrameStreamWriterLayer,
  projectionRuntimeRunnerLayer,
  projectionSourceReaderLayerMemory,
  timescaleFrameWriterLayerMemory,
  type FrameStreamWriterShape,
  type ProjectionSourceReaderShape,
  type TimescaleFrameWriterShape,
} from "./ProjectionRuntime.js"

export {
  ProjectionCaggAggregate,
  ProjectionCaggAggregateKind,
  ProjectionCaggCompileError,
  ProjectionCaggPlan,
  ProjectionCaggRefreshPolicy,
  ProjectionCaggSpec,
  compileProjectionCagg,
  compileProjectionCaggUnsafe,
  type ProjectionCaggAggregate as ProjectionCaggAggregateType,
  type ProjectionCaggAggregateKind as ProjectionCaggAggregateKindType,
  type ProjectionCaggPlan as ProjectionCaggPlanType,
  type ProjectionCaggRefreshPolicy as ProjectionCaggRefreshPolicyType,
  type ProjectionCaggSpec as ProjectionCaggSpecType,
} from "./ProjectionCagg.js"

export {
  ProjectionMigrationApplyFailed,
  ProjectionMigrationApplyRequest,
  ProjectionMigrationApplyResult,
  ProjectionMigrationApprovalMismatch,
  ProjectionMigrationApplier,
  ProjectionMigrationController,
  ProjectionMigrationPreview,
  ProjectionMigrationPreviewNotFound,
  ProjectionMigrationPreviewRequest,
  ProjectionMigrationRisk,
  ProjectionMigrationStatement,
  ProjectionMigrationWarning,
  projectionMigrationApplierLayerMemory,
  projectionMigrationControllerLayer,
  type MemoryProjectionMigrationApplierState,
  type ProjectionMigrationApplierShape,
  type ProjectionMigrationApplyRequest as ProjectionMigrationApplyRequestType,
  type ProjectionMigrationApplyResult as ProjectionMigrationApplyResultType,
  type ProjectionMigrationControllerShape,
  type ProjectionMigrationPreview as ProjectionMigrationPreviewType,
  type ProjectionMigrationPreviewRequest as ProjectionMigrationPreviewRequestType,
  type ProjectionMigrationRisk as ProjectionMigrationRiskType,
  type ProjectionMigrationStatement as ProjectionMigrationStatementType,
  type ProjectionMigrationWarning as ProjectionMigrationWarningType,
} from "./ProjectionMigration.js"

export {
  ProjectionWorkerAlreadyRunning,
  ProjectionWorkerNotFound,
  ProjectionWorkerRunner,
  ProjectionWorkerScheduler,
  noopProjectionWorkerRunnerLayer,
  projectionWorkerSchedulerLayer,
  projectionWorkerSchedulerLayerWithDurableLeases,
  projectionWorkerSchedulerLayerWithPorts,
  type ProjectionWorkerRunnerShape,
  type ProjectionWorkerSchedulerError,
  type ProjectionWorkerSchedulerShape,
} from "./ProjectionScheduler.js"

export {
  ProjectionNotFound,
  ProjectionRegistry,
  ProjectionRegistryEntry,
  ProjectionRegistryFilter,
  ProjectionRegistryStatus,
  projectionRegistryLayerMemory,
  type ProjectionRegistryEntry as ProjectionRegistryEntryType,
  type ProjectionRegistryFilter as ProjectionRegistryFilterType,
  type ProjectionRegistryShape,
  type ProjectionRegistryStatus as ProjectionRegistryStatusType,
  type RegisterProjectionOptions,
} from "./ProjectionRegistry.js"

export {
  ProjectionWorkerControl,
  ProjectionWorkerControlFailure,
  ProjectionWorkerNatsHost,
  makeProjectionWorkerNatsEndpoints,
  makeProjectionWorkerNatsHost,
  mapProjectionWorkerNatsError,
  projectionWorkerNatsHostLayer,
  type ProjectionWorkerControlShape,
  type ProjectionWorkerNatsHostShape,
} from "./ProjectionWorkerNatsHost.js"

export {
  DEFAULT_PROJECTION_WORKER_NATS_OPTIONS,
  ProjectionPlanRequest,
  ProjectionPlanResponse,
  ProjectionRunOnceRequest,
  ProjectionRunOnceResponse,
  ProjectionStartRequest,
  ProjectionStartResponse,
  ProjectionStatusRequest,
  ProjectionStatusResponse,
  ProjectionStopRequest,
  ProjectionStopResponse,
  ProjectionTailRequest,
  ProjectionTailResponse,
  ProjectionWorkerNatsOperation,
  ProjectionWorkerSelector,
  ProjectionWorkerStartMode,
  projectionWorkerNatsOperations,
  resolveProjectionWorkerNatsOptions,
  type ProjectionPlanRequest as ProjectionPlanRequestType,
  type ProjectionPlanResponse as ProjectionPlanResponseType,
  type ProjectionRunOnceRequest as ProjectionRunOnceRequestType,
  type ProjectionRunOnceResponse as ProjectionRunOnceResponseType,
  type ProjectionStartRequest as ProjectionStartRequestType,
  type ProjectionStartResponse as ProjectionStartResponseType,
  type ProjectionStatusRequest as ProjectionStatusRequestType,
  type ProjectionStatusResponse as ProjectionStatusResponseType,
  type ProjectionStopRequest as ProjectionStopRequestType,
  type ProjectionStopResponse as ProjectionStopResponseType,
  type ProjectionTailRequest as ProjectionTailRequestType,
  type ProjectionTailResponse as ProjectionTailResponseType,
  type ProjectionWorkerNatsOperation as ProjectionWorkerNatsOperationType,
  type ProjectionWorkerNatsOptions,
  type ProjectionWorkerSelector as ProjectionWorkerSelectorType,
  type ProjectionWorkerStartMode as ProjectionWorkerStartModeType,
  type ResolvedProjectionWorkerNatsOptions,
} from "./NatsMicroContracts.js"
