/**
 * GeniferBlock Schema
 *
 * Block type for rendering rich genifer UI trees within the terminal.
 * Enables hybrid terminal that can render both text/markdown responses
 * and structured UI components via the genifer system.
 *
 * @module terminal/v3/schemas/genifer-block
 */

import { Schema } from 'effect'
import type { UITree, JsonPatch } from '@/lib/genifer/core/schemas'

// =============================================================================
// Semantic Region Entry
// =============================================================================

/**
 * Entry describing a semantic region within the UI tree.
 * Used by agents to discover and target specific regions for transformation.
 */
export const SemanticRegionEntry = Schema.Struct({
  /** Unique region ID (matches data-semantic-id attribute) */
  id: Schema.String,
  /** Human-readable label (matches data-semantic-label attribute) */
  label: Schema.String,
  /** Region type for categorization */
  type: Schema.optional(Schema.String),
  /** Key of the element in the UITree that contains this region */
  elementKey: Schema.optional(Schema.String),
})
export type SemanticRegionEntry = typeof SemanticRegionEntry.Type

// =============================================================================
// GeniferBlock Schema
// =============================================================================

/**
 * GeniferBlock v3 - Rich UI rendering block
 *
 * This block type enables the terminal to render structured UI components
 * generated by AI tools using the genifer system. It supports:
 *
 * - Progressive streaming via patches
 * - Semantic regions for agent targeting
 * - Integration with the combined catalog (RVN + layout components)
 *
 * @example
 * ```tsx
 * // Creating a genifer block
 * const block = createGeniferBlock()
 *
 * // With initial tree
 * const block = createGeniferBlock(initialTree, true) // isStreaming = true
 *
 * // Rendering
 * <GeniferBlockComponent block={block} />
 * ```
 */
export const GeniferBlockV3 = Schema.TaggedStruct('genifer', {
  /** Unique block identifier */
  id: Schema.String,
  /** When the block was created */
  timestamp: Schema.DateFromSelf,
  /**
   * The UI tree to render.
   * null when streaming hasn't started or tree is being rebuilt.
   */
  uiTree: Schema.NullOr(Schema.Unknown), // UITree type - using Unknown for flexibility
  /**
   * Accumulated patches applied to the tree.
   * Useful for debugging and replay.
   */
  patches: Schema.Array(Schema.Unknown), // JsonPatch[] - using Unknown for flexibility
  /**
   * Whether the UI tree is currently streaming/updating.
   * Used to show loading states and defer certain interactions.
   */
  isStreaming: Schema.Boolean,
  /**
   * Discovered semantic regions within the UI tree.
   * Populated by scanning the tree for SemanticRegion elements.
   */
  semanticRegions: Schema.Array(SemanticRegionEntry),
})
export type GeniferBlockV3 = typeof GeniferBlockV3.Type

// =============================================================================
// Type Guard
// =============================================================================

/**
 * Type guard for GeniferBlock
 */
export const isGeniferBlock = (block: { _tag: string }): block is GeniferBlockV3 =>
  block._tag === 'genifer'

// =============================================================================
// Factory
// =============================================================================

let blockCounter = 0

const generateBlockId = (): string => {
  blockCounter++
  return `genifer-${Date.now()}-${blockCounter.toString(36)}`
}

/**
 * Create a new GeniferBlock
 *
 * @param uiTree - Initial UI tree (null if streaming)
 * @param isStreaming - Whether the block is in streaming mode
 * @returns A new GeniferBlockV3 instance
 */
export const createGeniferBlock = (
  uiTree: UITree | null = null,
  isStreaming: boolean = false,
): GeniferBlockV3 => ({
  _tag: 'genifer',
  id: generateBlockId(),
  timestamp: new Date(),
  uiTree: uiTree as unknown, // Cast to unknown for schema compatibility
  patches: [],
  isStreaming,
  semanticRegions: [],
})

/**
 * Create a GeniferBlock with semantic regions
 *
 * @param uiTree - The UI tree
 * @param semanticRegions - Pre-scanned semantic regions
 * @param isStreaming - Whether streaming is active
 * @returns A new GeniferBlockV3 instance
 */
export const createGeniferBlockWithRegions = (
  uiTree: UITree | null,
  semanticRegions: SemanticRegionEntry[],
  isStreaming: boolean = false,
): GeniferBlockV3 => ({
  _tag: 'genifer',
  id: generateBlockId(),
  timestamp: new Date(),
  uiTree: uiTree as unknown,
  patches: [],
  isStreaming,
  semanticRegions,
})
