/**
 * MorphCard Component
 *
 * Polymorphic card container that morphs between modes.
 * Supports both static renders and AI-generated content.
 *
 * @module morph-card/components/MorphCard
 */

import {
  type ReactNode,
  type ReactElement,
  type FC,
  useMemo,
  useCallback,
  useContext,
  useEffect,
} from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Option } from 'effect';
import { RegistryContext } from '@effect-atom/atom-react';
import { cn } from '@/lib/utils';
import type { CardId, CardMode, SizePreset } from '../schemas';
import type { TransitionGrammar, MorphCardConfig } from '../schemas';
import { grammarToVariants, DEFAULT_TRANSITION } from '../schemas/transition-grammar';
import { DEFAULT_CARD_CONFIG } from '../schemas/animation-config';
import { DEFAULT_SIZES } from '../schemas/card-state';
import { DEFAULT_GENERATIVE_STATE } from '../schemas/generative-state';
import { CardContext, useCardContextValue, useCardActions } from '../context';
import { generativeStateFamily } from '../atoms/generative-atoms';
import { AnimatedItem, ANIMATION_PRESETS } from './AnimatedItem';
import { MetricBlock, MetricGrid } from './MetricBlock';
import { GenerativeLoading, DecodeErrorBoundary } from './LoadingStates';
import { useGenerativeMode } from '../hooks/useGenerativeMode';
import { GenerativeDepthProvider } from '@/lib/json-render/react/generative';
import { Renderer, DefaultFallback } from '@/lib/json-render/react/renderer';
import { UITree } from '@/lib/json-render/core/schemas';
import type { DomainCatalog } from '@/lib/json-render/core/CatalogService';
import { Either, Schema } from 'effect';

// =============================================================================
// Types
// =============================================================================

/**
 * Render function type for mode-specific content
 */
export type ModeRender = () => ReactElement;

/**
 * Render registry mapping modes to render functions
 */
export type RenderRegistry = Partial<Record<CardMode, ModeRender>>;

/**
 * MorphCard Props
 */
export interface MorphCardProps {
  /** Unique card identifier */
  cardId: string;
  /** Initial mode */
  initialMode?: CardMode;
  /** Size presets for each mode */
  sizes?: Partial<Record<CardMode, SizePreset>>;
  /** Card configuration */
  config?: Partial<MorphCardConfig>;
  /** Transition grammar for mode changes */
  transition?: TransitionGrammar;
  /** Render registry mapping modes to render functions */
  renders?: RenderRegistry;
  /** Children (alternative to render registry) */
  children?: ReactNode | ((mode: CardMode) => ReactNode);
  /** Additional className */
  className?: string;
  /** Whether card is interactive (hover effects) */
  interactive?: boolean;
  /** Click handler */
  onClick?: () => void;
  /** Mode change handler */
  onModeChange?: (mode: CardMode, previousMode: CardMode) => void;

  // ==========================================================================
  // Generative Props
  // ==========================================================================

  /** Enable generative mode - content generated by AI */
  generative?: boolean;
  /** Prompt template (use {{mode}} for interpolation) */
  prompt?: string;
  /** Additional context for AI generation */
  generativeContext?: Record<string, unknown>;
  /** API endpoint for generation */
  generativeApi?: string;
  /** Component catalog for rendering generated content */
  componentCatalog?: DomainCatalog;
  /** Custom loading text during generation */
  loadingText?: string;
}

// =============================================================================
// Component
// =============================================================================

/**
 * MorphCard - Polymorphic card container
 *
 * Can be used in three ways:
 *
 * 1. **Render Registry** - Map modes to render functions
 * ```tsx
 * <MorphCard
 *   cardId="status-card"
 *   initialMode="compact"
 *   renders={{
 *     idle: () => <IdleView />,
 *     compact: () => <CompactView />,
 *     expanded: () => <ExpandedView />,
 *   }}
 * />
 * ```
 *
 * 2. **Render Function** - Single function receiving current mode
 * ```tsx
 * <MorphCard cardId="data-card">
 *   {(mode) => mode === 'expanded' ? <FullView /> : <SummaryView />}
 * </MorphCard>
 * ```
 *
 * 3. **Generative Mode** - AI-generated content per mode
 * ```tsx
 * <MorphCard
 *   cardId="gen-card"
 *   generative
 *   prompt="Generate a {{mode}} view of system metrics"
 *   componentCatalog={tmnlCatalog}
 * />
 * ```
 */
function MorphCardRoot({
  cardId,
  initialMode: _initialMode = 'default',
  sizes: sizesProp,
  config: configProp,
  transition: transitionProp,
  renders,
  children,
  className,
  interactive = true,
  onClick,
  onModeChange: _onModeChange,
  // Generative props
  generative = false,
  prompt,
  generativeContext,
  generativeApi,
  componentCatalog: _componentCatalog,
  loadingText,
}: MorphCardProps) {
  const normalizedId = cardId as CardId;
  const registry = useContext(RegistryContext);

  // Build context value
  const contextValue = useCardContextValue(normalizedId);
  const actions = useCardActions(normalizedId);

  // Initialize generative state if enabled
  useEffect(() => {
    if (generative && prompt) {
      const currentState = registry.get(generativeStateFamily(normalizedId));
      // Only update if not already enabled or prompt changed
      if (!currentState.enabled || currentState.prompt !== prompt) {
        registry.set(generativeStateFamily(normalizedId), {
          ...DEFAULT_GENERATIVE_STATE,
          enabled: true,
          prompt,
          context: generativeContext,
          api: generativeApi,
          modes: { ...DEFAULT_GENERATIVE_STATE.modes },
        });
      }
    }
  }, [generative, prompt, generativeContext, generativeApi, normalizedId, registry]);

  // Generative mode hook
  const genMode = useGenerativeMode(normalizedId);

  // Merge sizes
  const sizes = useMemo(
    () => ({ ...DEFAULT_SIZES, ...sizesProp }),
    [sizesProp]
  );

  // Merge config
  const config = useMemo(
    () => ({ ...DEFAULT_CARD_CONFIG, ...configProp }),
    [configProp]
  );

  // Active transition
  const transition = transitionProp ?? contextValue.transition ?? DEFAULT_TRANSITION;
  const variants = useMemo(() => grammarToVariants(transition), [transition]);

  // Current mode and dimensions
  const { mode, isHovered } = contextValue.state;
  const currentSize = sizes[mode] ?? sizes.default;

  // Handle hover
  const handleMouseEnter = useCallback(() => {
    if (interactive) actions.setHovered(true);
  }, [interactive, actions]);

  const handleMouseLeave = useCallback(() => {
    if (interactive) actions.setHovered(false);
  }, [interactive, actions]);

  // Resolve content (static vs generative)
  const staticContent = useMemo(() => {
    // Render registry takes precedence
    if (renders && renders[mode]) {
      return renders[mode]!();
    }
    // Render function
    if (typeof children === 'function') {
      return children(mode);
    }
    // Static children
    return children;
  }, [renders, children, mode]);

  // Generative content rendering with proper error boundary
  const generativeContent = useMemo(() => {
    if (!generative || !genMode.isEnabled) return null;

    // If we have content, render it using the json-render Renderer
    if (Option.isSome(genMode.content)) {
      const { root, elements } = genMode.content.value;
      const isStreaming = genMode.status === 'streaming';

      // Decode UITree from plain objects using Schema.decodeUnknownEither
      // Returns Either<ParseError, UITree> for proper error handling
      const decodeResult = Schema.decodeUnknownEither(UITree)({
        root: root ?? '',
        elements: elements as Record<string, unknown>,
      });

      // During streaming, partial content is expected - use empty tree as placeholder
      if (Either.isLeft(decodeResult)) {
        if (isStreaming) {
          // Streaming: partial content expected, show placeholder
          return (
            <GenerativeDepthProvider prompt={prompt}>
              <Renderer
                tree={UITree.empty()}
                loading={true}
                fallback={DefaultFallback}
              />
            </GenerativeDepthProvider>
          );
        }

        // Not streaming but decode failed - this is a real error
        // Return error boundary placeholder (GenerativeLoading will wrap with error UI)
        return (
          <DecodeErrorBoundary
            error={decodeResult.left}
            onRetry={genMode.retry}
          />
        );
      }

      // Successful decode
      return (
        <GenerativeDepthProvider prompt={prompt}>
          <Renderer
            tree={decodeResult.right}
            loading={isStreaming}
            fallback={DefaultFallback}
          />
        </GenerativeDepthProvider>
      );
    }

    return null;
  }, [generative, genMode.isEnabled, genMode.content, genMode.status, genMode.retry, prompt]);

  // Final content (wrapped in loading state if generative)
  const finalContent = useMemo(() => {
    if (generative && genMode.isEnabled) {
      return (
        <GenerativeLoading
          status={genMode.status}
          progress={genMode.progress}
          error={genMode.error}
          onRetry={genMode.retry}
          loadingText={loadingText}
        >
          {generativeContent || staticContent}
        </GenerativeLoading>
      );
    }
    return staticContent;
  }, [
    generative,
    genMode.isEnabled,
    genMode.status,
    genMode.progress,
    genMode.error,
    genMode.retry,
    generativeContent,
    staticContent,
    loadingText,
  ]);

  // Border glow based on config
  const borderGlow = useMemo(() => {
    const intensity = config.borderIntensity ?? 0.15;
    return `
      inset 0 0 0 1px rgba(255,255,255,${intensity}),
      inset 0 1px 0 rgba(255,255,255,${intensity * 0.8}),
      0 0 0 1px rgba(255,255,255,${intensity * 0.3}),
      0 2px 8px rgba(0,0,0,0.4),
      0 0 20px rgba(0,0,0,0.2)
    `;
  }, [config.borderIntensity]);

  return (
    <CardContext.Provider value={contextValue}>
      <motion.div
        className={cn(
          'relative will-change-transform',
          interactive && 'cursor-pointer',
          className
        )}
        data-card-id={cardId}
        data-mode={mode}
        data-generative={generative}
        onClick={onClick}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        animate={{
          width: currentSize.width,
          height: currentSize.height,
        }}
        transition={{
          type: 'spring',
          stiffness: config.spring?.stiffness ?? 400,
          damping: config.spring?.damping ?? 30,
          mass: config.spring?.mass ?? 0.8,
        }}
      >
        {/* Main container */}
        <motion.div
          className="relative w-full h-full overflow-hidden"
          style={{
            backgroundColor: 'oklch(0.08 0.005 280)',
            borderRadius: config.borderRadius ?? 16,
            boxShadow: borderGlow,
          }}
          layout
        >
          {/* Content with transition animation */}
          <AnimatePresence mode="wait">
            <motion.div
              key={`${mode}-${generative ? 'gen' : 'static'}`}
              className="absolute inset-0"
              initial={variants.initial as any}
              animate={variants.animate as any}
              exit={variants.exit as any}
            >
              {finalContent}
            </motion.div>
          </AnimatePresence>

          {/* Hover highlight */}
          {interactive && isHovered && (
            <motion.div
              className="absolute inset-0 pointer-events-none"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              style={{
                background: 'linear-gradient(180deg, rgba(255,255,255,0.02) 0%, transparent 50%)',
                borderRadius: config.borderRadius ?? 16,
              }}
            />
          )}
        </motion.div>
      </motion.div>
    </CardContext.Provider>
  );
}

// =============================================================================
// Sub-components
// =============================================================================

/**
 * MorphCard.Content - Content wrapper with padding
 */
interface ContentProps {
  children: ReactNode;
  className?: string;
  padding?: 'none' | 'sm' | 'md' | 'lg';
}

const PADDING_STYLES = {
  none: '',
  sm: 'p-2',
  md: 'p-4',
  lg: 'p-6',
};

const Content: FC<ContentProps> = ({ children, className, padding = 'md' }) => (
  <div className={cn('w-full h-full', PADDING_STYLES[padding], className)}>
    {children}
  </div>
);

/**
 * MorphCard.Header - Card header area
 */
interface HeaderProps {
  children: ReactNode;
  className?: string;
}

const Header: FC<HeaderProps> = ({ children, className }) => (
  <div
    className={cn(
      'flex items-center justify-between px-4 py-2',
      'border-b border-white/5',
      className
    )}
  >
    {children}
  </div>
);

/**
 * MorphCard.Title - Card title
 */
interface TitleProps {
  children: ReactNode;
  className?: string;
  size?: 'sm' | 'md' | 'lg';
}

const TITLE_SIZES = {
  sm: 'text-xs',
  md: 'text-sm',
  lg: 'text-base',
};

const Title: FC<TitleProps> = ({ children, className, size = 'md' }) => (
  <span
    className={cn(
      'font-mono font-medium text-neutral-200 tracking-wide uppercase',
      TITLE_SIZES[size],
      className
    )}
  >
    {children}
  </span>
);

/**
 * MorphCard.Badge - Status badge
 */
interface BadgeProps {
  children: ReactNode;
  variant?: 'default' | 'success' | 'warning' | 'error' | 'info';
  className?: string;
}

const BADGE_VARIANTS = {
  default: 'bg-neutral-800 text-neutral-300',
  success: 'bg-emerald-900/50 text-emerald-400',
  warning: 'bg-amber-900/50 text-amber-400',
  error: 'bg-red-900/50 text-red-400',
  info: 'bg-cyan-900/50 text-cyan-400',
};

const Badge: FC<BadgeProps> = ({ children, variant = 'default', className }) => (
  <span
    className={cn(
      'px-2 py-0.5 rounded text-[10px] font-mono uppercase tracking-wider',
      BADGE_VARIANTS[variant],
      className
    )}
  >
    {children}
  </span>
);

/**
 * MorphCard.Body - Main content area
 */
interface BodyProps {
  children: ReactNode;
  className?: string;
}

const Body: FC<BodyProps> = ({ children, className }) => (
  <div className={cn('flex-1 overflow-hidden', className)}>{children}</div>
);

/**
 * MorphCard.Footer - Card footer area
 */
interface FooterProps {
  children: ReactNode;
  className?: string;
}

const Footer: FC<FooterProps> = ({ children, className }) => (
  <div
    className={cn(
      'flex items-center justify-between px-4 py-2',
      'border-t border-white/5',
      className
    )}
  >
    {children}
  </div>
);

/**
 * MorphCard.Actions - Action button container
 */
interface ActionsProps {
  children: ReactNode;
  className?: string;
}

const Actions: FC<ActionsProps> = ({ children, className }) => (
  <div className={cn('flex items-center gap-2', className)}>{children}</div>
);

// =============================================================================
// Compound Component Export
// =============================================================================

/**
 * MorphCard compound component with all sub-components
 */
export const MorphCard = Object.assign(MorphCardRoot, {
  Content,
  Header,
  Title,
  Badge,
  Body,
  Footer,
  Actions,
  // Re-export related components
  AnimatedItem,
  MetricBlock,
  MetricGrid,
  // Re-export presets
  ANIMATION_PRESETS,
});

export default MorphCard;
