/**
 * IIoT Centralized Tags
 *
 * ALL tags in one file. Named exports only. No hardcoded strings anywhere else.
 * Single source of truth for schema tags, RPC tags, entity tags, and workflow tags.
 *
 * @module
 */

// =============================================================================
// Schema Tags (from TaggedStruct _tag field values)
// =============================================================================

// Readings
export const SensorReadingTag = 'SensorReading' as const
export const AggregatedReadingTag = 'AggregatedReading' as const
export const AnalyticsRecordTag = 'AnalyticsRecord' as const

// Alarms
export const AlarmTag = 'Alarm' as const
export const AlarmContextTag = 'AlarmContext' as const

// Assets
export const PlantTag = 'Plant' as const
export const LineTag = 'Line' as const
export const MachineTag = 'Machine' as const
export const SensorTag = 'Sensor' as const
export const SensorHierarchyTag = 'SensorHierarchy' as const
export const MachineWithSensorsTag = 'MachineWithSensors' as const
export const LineWithMachinesTag = 'LineWithMachines' as const
export const PlantHierarchyTag = 'PlantHierarchy' as const

// =============================================================================
// RPC Tags (Schema tag + method)
// =============================================================================

// Sensor RPCs
export const SensorReadingGetLatestTag = `${SensorReadingTag}.GetLatest` as const
export const SensorReadingQueryTag = `${SensorReadingTag}.Query` as const
export const SensorReadingSubscribeTag = `${SensorReadingTag}.Subscribe` as const
export const AggregatedReadingQueryTag = `${AggregatedReadingTag}.Query` as const

// Asset RPCs
export const SensorHierarchyGetTag = `${SensorHierarchyTag}.Get` as const
export const PlantHierarchyGetTag = `${PlantHierarchyTag}.Get` as const
export const MachineGetWithSensorsTag = `${MachineTag}.GetWithSensors` as const
export const PlantGetTag = `${PlantTag}.Get` as const
export const PlantListTag = `${PlantTag}.List` as const
export const LineListForPlantTag = `${LineTag}.ListForPlant` as const
export const MachineListForLineTag = `${MachineTag}.ListForLine` as const
export const SensorListForMachineTag = `${SensorTag}.ListForMachine` as const

// Alarm Query RPCs (stateless)
export const AlarmQueryTag = `${AlarmTag}.Query` as const
export const AlarmContextGetTag = `${AlarmContextTag}.Get` as const
export const AlarmGetStatsTag = `${AlarmTag}.GetStats` as const

// =============================================================================
// Alarm Entity Tags
// EntityProxy derives tags as `${Entity.type}.${rpc._tag}`
// =============================================================================

export const AlarmEntityType = AlarmTag
export const AlarmCreateTag = `${AlarmEntityType}.Create` as const
export const AlarmGetTag = `${AlarmEntityType}.Get` as const
export const AlarmAcknowledgeTag = `${AlarmEntityType}.Acknowledge` as const
export const AlarmClearTag = `${AlarmEntityType}.Clear` as const

// Discard variants (fire-and-forget) - auto-generated by EntityProxy
export const AlarmCreateDiscardTag = `${AlarmEntityType}.CreateDiscard` as const
export const AlarmAcknowledgeDiscardTag = `${AlarmEntityType}.AcknowledgeDiscard` as const
export const AlarmClearDiscardTag = `${AlarmEntityType}.ClearDiscard` as const

// =============================================================================
// Workflow Tags
// =============================================================================

export const AlarmLifecycleWorkflowTag = 'AlarmLifecycle' as const
export const MonitorDeviceWorkflowTag = 'MonitorDevice' as const

// Workflow RPC variants (generated by WorkflowProxy)
// Format: WorkflowName (execute), WorkflowNameDiscard (fire-and-forget), WorkflowNameResume
export const AlarmLifecycleExecuteTag = AlarmLifecycleWorkflowTag
export const AlarmLifecycleDiscardTag = 'AlarmLifecycleDiscard' as const
export const AlarmLifecycleResumeTag = 'AlarmLifecycleResume' as const

export const MonitorDeviceExecuteTag = MonitorDeviceWorkflowTag
export const MonitorDeviceDiscardTag = 'MonitorDeviceDiscard' as const
export const MonitorDeviceResumeTag = 'MonitorDeviceResume' as const

// =============================================================================
// Activity Tags (for workflow activities)
// =============================================================================

export const CheckReadingActivityTag = 'CheckReading' as const
export const ProcessAcknowledgmentActivityTag = 'ProcessAcknowledgment' as const
export const AutoClearActivityTag = 'AutoClear' as const
export const SendNotificationActivityTag = 'SendNotification' as const

// =============================================================================
// DurableDeferred Tags (for external signals)
// =============================================================================

export const AlarmAckDeferredPrefix = 'AlarmAck' as const
export const makeAlarmAckDeferredTag = (alarmId: string): string =>
  `${AlarmAckDeferredPrefix}-${alarmId}`

// =============================================================================
// DurableClock Tags (for timed operations)
// =============================================================================

export const SuppressionTimeoutPrefix = 'SuppressionTimeout' as const
export const makeSuppressionTimeoutTag = (alarmId: string): string =>
  `${SuppressionTimeoutPrefix}-${alarmId}`

export const MonitorPollPrefix = 'MonitorPoll' as const
export const makeMonitorPollTag = (deviceId: string, timestamp: number): string =>
  `${MonitorPollPrefix}-${deviceId}-${timestamp}`

// =============================================================================
// Service Tags (for Effect.Service)
// =============================================================================

export const TimeSeriesClientTag = 'iiot/TimeSeriesClient' as const
export const GraphClientTag = 'iiot/GraphClient' as const
export const SensorServiceTag = 'iiot/SensorService' as const
export const AssetServiceTag = 'iiot/AssetService' as const
export const AlarmServiceTag = 'iiot/AlarmService' as const
export const IIoTServiceTag = 'iiot/IIoTService' as const
export const IIoTClientTag = 'iiot/IIoTClient' as const
export const IIoTPgClientTag = 'iiot/IIoTPgClient' as const

// =============================================================================
// Type Exports for Tag Values
// =============================================================================

export type SensorReadingTag = typeof SensorReadingTag
export type AggregatedReadingTag = typeof AggregatedReadingTag
export type AlarmTag = typeof AlarmTag
export type AlarmContextTag = typeof AlarmContextTag
export type SensorHierarchyTag = typeof SensorHierarchyTag
export type PlantHierarchyTag = typeof PlantHierarchyTag
export type MachineTag = typeof MachineTag
export type SensorTag = typeof SensorTag
export type AlarmEntityType = typeof AlarmEntityType
export type AlarmLifecycleWorkflowTag = typeof AlarmLifecycleWorkflowTag
export type MonitorDeviceWorkflowTag = typeof MonitorDeviceWorkflowTag
