/**
 * Type declaration for virtual:component-sources module
 *
 * This module is generated by vite-plugin-source-extract.ts
 */

declare module 'virtual:component-sources' {
  export interface ComponentSourceMeta {
    id: string
    label: string
    source: string
    filePath: string
    lineNumber: number
  }

  export const sources: Record<string, ComponentSourceMeta>
  export function getSource(id: string): string | null
  export function getSourceMeta(id: string): ComponentSourceMeta | null
  export default sources
}
