/**
 * MorphCard Domain Catalog
 *
 * JSON-render catalog for polymorphic card components.
 * Enables AI-driven card generation with morphing container pattern.
 *
 * @module morph-card/catalog
 */

import { Schema } from 'effect';
import type { DomainCatalog, ComponentRenderProps } from '@/lib/json-render/core/CatalogService';
import type { EntranceAnimation } from '@/lib/json-render/core/animation-schema';

import { MorphCard, AnimatedItem, MetricBlock, MetricGrid, type MetricStatus } from '../components';
import type { CardMode } from '../schemas';

// =============================================================================
// Prop Schemas
// =============================================================================

/**
 * MorphCard props schema
 */
const MorphCardPropsSchema = Schema.Struct({
  /** Unique card identifier */
  cardId: Schema.String,
  /** Initial display mode */
  initialMode: Schema.optional(Schema.Literal('idle', 'compact', 'default', 'expanded', 'detail')),
  /** Custom size for idle mode */
  idleSize: Schema.optional(Schema.Struct({
    width: Schema.Number,
    height: Schema.Number,
  })),
  /** Custom size for compact mode */
  compactSize: Schema.optional(Schema.Struct({
    width: Schema.Number,
    height: Schema.Number,
  })),
  /** Custom size for default mode */
  defaultSize: Schema.optional(Schema.Struct({
    width: Schema.Number,
    height: Schema.Number,
  })),
  /** Custom size for expanded mode */
  expandedSize: Schema.optional(Schema.Struct({
    width: Schema.Number,
    height: Schema.Number,
  })),
  /** Custom size for detail mode */
  detailSize: Schema.optional(Schema.Struct({
    width: Schema.Number,
    height: Schema.Number,
  })),
  /** Border radius */
  borderRadius: Schema.optional(Schema.Number),
  /** Enable motion blur on transitions */
  motionBlur: Schema.optional(Schema.Boolean),
  /** Whether card is interactive (hover effects) */
  interactive: Schema.optional(Schema.Boolean),
  /** Additional className */
  className: Schema.optional(Schema.String),
  // Generative props
  /** Enable generative mode - content generated by AI */
  generative: Schema.optional(Schema.Boolean),
  /** Prompt template (use {{mode}} for mode interpolation) */
  prompt: Schema.optional(Schema.String),
  /** Additional context for AI generation */
  generativeContext: Schema.optional(Schema.Record({
    key: Schema.String,
    value: Schema.Unknown,
  })),
  /** API endpoint override for generation */
  generativeApi: Schema.optional(Schema.String),
  /** Custom loading text during generation */
  loadingText: Schema.optional(Schema.String),
});

/**
 * MorphCard.Content props schema
 */
const MorphCardContentPropsSchema = Schema.Struct({
  padding: Schema.optional(Schema.Literal('none', 'sm', 'md', 'lg')),
  className: Schema.optional(Schema.String),
});

/**
 * MorphCard.Header props schema
 */
const MorphCardHeaderPropsSchema = Schema.Struct({
  className: Schema.optional(Schema.String),
});

/**
 * MorphCard.Title props schema
 */
const MorphCardTitlePropsSchema = Schema.Struct({
  text: Schema.String,
  size: Schema.optional(Schema.Literal('sm', 'md', 'lg')),
  className: Schema.optional(Schema.String),
});

/**
 * MorphCard.Badge props schema
 */
const MorphCardBadgePropsSchema = Schema.Struct({
  text: Schema.String,
  variant: Schema.optional(Schema.Literal('default', 'success', 'warning', 'error', 'info')),
  className: Schema.optional(Schema.String),
});

/**
 * MorphCard.Body props schema
 */
const MorphCardBodyPropsSchema = Schema.Struct({
  className: Schema.optional(Schema.String),
});

/**
 * MorphCard.Footer props schema
 */
const MorphCardFooterPropsSchema = Schema.Struct({
  className: Schema.optional(Schema.String),
});

/**
 * AnimatedItem props schema
 */
const AnimatedItemPropsSchema = Schema.Struct({
  /** Index for stagger delay */
  index: Schema.optional(Schema.Number),
  /** Animation style */
  style: Schema.optional(Schema.Literal('fade', 'slide', 'scale', 'blur', 'glitch')),
  /** Direction for slide animations */
  from: Schema.optional(Schema.Literal('left', 'right', 'top', 'bottom')),
  /** Stagger delay in seconds */
  stagger: Schema.optional(Schema.Number),
  /** Duration in seconds */
  duration: Schema.optional(Schema.Number),
  /** Additional className */
  className: Schema.optional(Schema.String),
});

/**
 * MetricBlock props schema
 */
const MetricBlockPropsSchema = Schema.Struct({
  /** Metric label */
  label: Schema.String,
  /** Metric value */
  value: Schema.String,
  /** Status indicator */
  status: Schema.optional(Schema.Literal('nominal', 'warning', 'error', 'active', 'inactive')),
  /** Show status dot */
  showDot: Schema.optional(Schema.Boolean),
  /** Size variant */
  size: Schema.optional(Schema.Literal('sm', 'md', 'lg')),
  /** Additional className */
  className: Schema.optional(Schema.String),
});

/**
 * MetricGrid props schema
 */
const MetricGridPropsSchema = Schema.Struct({
  /** Number of columns */
  columns: Schema.optional(Schema.Literal(2, 3, 4)),
  /** Gap size */
  gap: Schema.optional(Schema.Literal('sm', 'md', 'lg')),
  /** Additional className */
  className: Schema.optional(Schema.String),
});

// =============================================================================
// Renderers
// =============================================================================

function MorphCardRenderer({ element, children }: ComponentRenderProps) {
  const props = element.props;

  // Build sizes object from individual size props
  const sizes: Partial<Record<CardMode, { width: number; height: number }>> = {};
  if (props['idleSize']) sizes.idle = props['idleSize'] as { width: number; height: number };
  if (props['compactSize']) sizes.compact = props['compactSize'] as { width: number; height: number };
  if (props['defaultSize']) sizes.default = props['defaultSize'] as { width: number; height: number };
  if (props['expandedSize']) sizes.expanded = props['expandedSize'] as { width: number; height: number };
  if (props['detailSize']) sizes.detail = props['detailSize'] as { width: number; height: number };

  // Build config object
  const config: { borderRadius?: number; motionBlur?: boolean } = {};
  if (props['borderRadius'] !== undefined) config.borderRadius = props['borderRadius'] as number;
  if (props['motionBlur'] !== undefined) config.motionBlur = props['motionBlur'] as boolean;

  return (
    <MorphCard
      cardId={(props['cardId'] as string) ?? element.key}
      initialMode={(props['initialMode'] as CardMode) ?? 'default'}
      sizes={Object.keys(sizes).length > 0 ? sizes : undefined}
      config={Object.keys(config).length > 0 ? config : undefined}
      interactive={(props['interactive'] as boolean) ?? true}
      className={props['className'] as string}
      generative={(props['generative'] as boolean) ?? false}
      prompt={props['prompt'] as string}
      generativeContext={props['generativeContext'] as Record<string, unknown>}
      generativeApi={props['generativeApi'] as string}
      loadingText={props['loadingText'] as string}
    >
      {children}
    </MorphCard>
  );
}

function MorphCardContentRenderer({ element, children }: ComponentRenderProps) {
  return (
    <MorphCard.Content
      padding={(element.props['padding'] as 'none' | 'sm' | 'md' | 'lg') ?? 'md'}
      className={element.props['className'] as string}
    >
      {children}
    </MorphCard.Content>
  );
}

function MorphCardHeaderRenderer({ element, children }: ComponentRenderProps) {
  return (
    <MorphCard.Header className={element.props['className'] as string}>
      {children}
    </MorphCard.Header>
  );
}

function MorphCardTitleRenderer({ element }: ComponentRenderProps) {
  return (
    <MorphCard.Title
      size={(element.props['size'] as 'sm' | 'md' | 'lg') ?? 'md'}
      className={element.props['className'] as string}
    >
      {element.props['text'] as string}
    </MorphCard.Title>
  );
}

function MorphCardBadgeRenderer({ element }: ComponentRenderProps) {
  return (
    <MorphCard.Badge
      variant={(element.props['variant'] as 'default' | 'success' | 'warning' | 'error' | 'info') ?? 'default'}
      className={element.props['className'] as string}
    >
      {element.props['text'] as string}
    </MorphCard.Badge>
  );
}

function MorphCardBodyRenderer({ element, children }: ComponentRenderProps) {
  return (
    <MorphCard.Body className={element.props['className'] as string}>
      {children}
    </MorphCard.Body>
  );
}

function MorphCardFooterRenderer({ element, children }: ComponentRenderProps) {
  return (
    <MorphCard.Footer className={element.props['className'] as string}>
      {children}
    </MorphCard.Footer>
  );
}

function AnimatedItemRenderer({ element, children }: ComponentRenderProps) {
  const config: {
    style?: 'fade' | 'slide' | 'scale' | 'blur' | 'glitch';
    from?: 'left' | 'right' | 'top' | 'bottom';
    stagger?: number;
    duration?: number;
  } = {};
  if (element.props['style']) config.style = element.props['style'] as typeof config.style;
  if (element.props['from']) config.from = element.props['from'] as typeof config.from;
  if (element.props['stagger']) config.stagger = element.props['stagger'] as number;
  if (element.props['duration']) config.duration = element.props['duration'] as number;

  return (
    <AnimatedItem
      index={(element.props['index'] as number) ?? 0}
      config={config}
      className={element.props['className'] as string}
    >
      {children}
    </AnimatedItem>
  );
}

function MetricBlockRenderer({ element }: ComponentRenderProps) {
  return (
    <MetricBlock
      label={element.props['label'] as string}
      value={element.props['value'] as string}
      status={(element.props['status'] as MetricStatus) ?? 'nominal'}
      showDot={(element.props['showDot'] as boolean) ?? true}
      size={(element.props['size'] as 'sm' | 'md' | 'lg') ?? 'md'}
      className={element.props['className'] as string}
    />
  );
}

function MetricGridRenderer({ element, children }: ComponentRenderProps) {
  return (
    <MetricGrid
      columns={(element.props['columns'] as 2 | 3 | 4) ?? 2}
      gap={(element.props['gap'] as 'sm' | 'md' | 'lg') ?? 'md'}
      className={element.props['className'] as string}
    >
      {children}
    </MetricGrid>
  );
}

// =============================================================================
// Default Entrance Animations
// =============================================================================

const defaultAnimations = {
  /** MorphCard container - smooth lift */
  card: {
    property: 'opacity+translateY',
    easing: 'out-cubic',
    duration: 'normal',
  } satisfies EntranceAnimation,

  /** Card structure (header, footer) - subtle fade */
  structure: {
    property: 'opacity',
    easing: 'out-quad',
    duration: 'fast',
  } satisfies EntranceAnimation,

  /** Interactive elements (badges) - snappy pop */
  badge: {
    property: 'opacity+scale',
    easing: 'out-back',
    duration: 'fast',
  } satisfies EntranceAnimation,

  /** AnimatedItem - handled by component, but provide fallback */
  item: {
    property: 'opacity',
    easing: 'out-quad',
    duration: 'fast',
  } satisfies EntranceAnimation,

  /** MetricBlock - quick fade-in */
  metric: {
    property: 'opacity+translateY',
    easing: 'out-quart',
    duration: 'fast',
  } satisfies EntranceAnimation,
};

// =============================================================================
// Domain Catalog Export
// =============================================================================

/**
 * MorphCard Domain Catalog
 *
 * Polymorphic card system for AI generation with:
 * - Morphing container that transitions between modes
 * - Stagger animation wrapper for coordinated entrances
 * - Metric display components for dashboard-style cards
 *
 * ## Usage Pattern
 *
 * ```json
 * {
 *   "type": "MorphCard",
 *   "props": {
 *     "cardId": "system-status",
 *     "initialMode": "default",
 *     "defaultSize": { "width": 320, "height": 120 }
 *   },
 *   "children": [
 *     {
 *       "type": "MorphCardContent",
 *       "props": { "padding": "md" },
 *       "children": [
 *         {
 *           "type": "AnimatedItem",
 *           "props": { "index": 0, "style": "slide", "from": "top" },
 *           "children": [...]
 *         }
 *       ]
 *     }
 *   ]
 * }
 * ```
 */
export const morphCardDomainCatalog: DomainCatalog = {
  name: 'MorphCard',
  components: {
    // Root container
    MorphCard: {
      schema: MorphCardPropsSchema,
      renderer: MorphCardRenderer,
      description: `Polymorphic card container that morphs between modes (idle, compact, default, expanded, detail).
      Supports both static renders and AI-generated content.

      STATIC MODE: Provide children or use renders prop for mode-specific content.
      GENERATIVE MODE: Set generative=true with prompt. Content generated per mode on first visit, then cached.

      Prompt interpolation: Use {{mode}} to inject current mode name.
      Example: "Generate a {{mode}} view of system metrics"

      Loading states include morphing placeholder, scramble animations, and progressive reveal as content streams in.

      REQUIRED: Always provide cardId for per-card state isolation.
      SIZING: Set *Size props (idleSize, defaultSize, etc.) for custom dimensions per mode.`,
      hasChildren: true,
      defaultEntrance: defaultAnimations.card,
    },

    // Structure components
    MorphCardContent: {
      schema: MorphCardContentPropsSchema,
      renderer: MorphCardContentRenderer,
      description: 'Content wrapper with configurable padding. Use inside MorphCard.',
      hasChildren: true,
      defaultEntrance: defaultAnimations.structure,
    },
    MorphCardHeader: {
      schema: MorphCardHeaderPropsSchema,
      renderer: MorphCardHeaderRenderer,
      description: 'Card header section with border. Contains title and badges.',
      hasChildren: true,
      defaultEntrance: defaultAnimations.structure,
    },
    MorphCardTitle: {
      schema: MorphCardTitlePropsSchema,
      renderer: MorphCardTitleRenderer,
      description: 'Card title with monospace font and uppercase styling. Sizes: sm, md, lg.',
      hasChildren: false,
      defaultEntrance: defaultAnimations.structure,
    },
    MorphCardBadge: {
      schema: MorphCardBadgePropsSchema,
      renderer: MorphCardBadgeRenderer,
      description: 'Status badge with variants: default, success, warning, error, info.',
      hasChildren: false,
      defaultEntrance: defaultAnimations.badge,
    },
    MorphCardBody: {
      schema: MorphCardBodyPropsSchema,
      renderer: MorphCardBodyRenderer,
      description: 'Main content area within MorphCard.',
      hasChildren: true,
      defaultEntrance: defaultAnimations.structure,
    },
    MorphCardFooter: {
      schema: MorphCardFooterPropsSchema,
      renderer: MorphCardFooterRenderer,
      description: 'Card footer section with border. Good for action buttons.',
      hasChildren: true,
      defaultEntrance: defaultAnimations.structure,
    },

    // Animation wrapper
    AnimatedItem: {
      schema: AnimatedItemPropsSchema,
      renderer: AnimatedItemRenderer,
      description: `Stagger animation wrapper for coordinated item entrances.
      Use index prop for stagger delay calculation (index * stagger seconds).
      Styles: fade (default), slide (with from direction), scale (pop-in), blur (reveal), glitch (cyberpunk).
      PATTERN: Wrap each item in AnimatedItem with incrementing index for cascade effect.`,
      hasChildren: true,
      defaultEntrance: defaultAnimations.item,
    },

    // Metric components
    MetricBlock: {
      schema: MetricBlockPropsSchema,
      renderer: MetricBlockRenderer,
      description: `Atomic metric display with label, value, and status indicator.
      Statuses: nominal (green), warning (amber), error (red), active (cyan), inactive (gray).
      Sizes: sm (tiny), md (default), lg (prominent).
      PATTERN: Use inside MetricGrid for dashboard layouts.`,
      hasChildren: false,
      defaultEntrance: defaultAnimations.metric,
    },
    MetricGrid: {
      schema: MetricGridPropsSchema,
      renderer: MetricGridRenderer,
      description: 'Grid layout for MetricBlock components. Columns: 2, 3, or 4. Gap: sm, md, lg.',
      hasChildren: true,
      defaultEntrance: defaultAnimations.structure,
    },
  },
};

export default morphCardDomainCatalog;
