/**
 * Axiom Ontology as Code (OaC) Target
 *
 * Generates complete repository structures for Palantir Foundry
 * Ontology as Code (Beta) deployment via Marketplace.
 *
 * Workflow: Axiom Schema → OaC Repo → Git Tag → Marketplace Install → Foundry
 */

import { Effect } from "effect"
import { mkdirSync, writeFileSync } from "fs"
import { join } from "path"
import type { ObjectSchema, LinkType, LinkCardinality } from "../object"
import { isLink } from "../object"
import {
  isPrimaryKey,
  isTitle,
  isNullable,
  hasDisplayName,
  hasDescription,
} from "../modifiers"
import { compileToOSDK, extractLinks, type OSDKObjectDefinition } from "./osdk"
import { MissingPrimaryKeyError, type CompileError } from "../errors"
import type { FieldRecord } from "../types"

// =============================================================================
// Configuration Types
// =============================================================================

/**
 * Configuration for generating a complete Ontology as Code repository
 */
export interface OntologyAsCodeConfig {
  /** Foundry namespace (e.g., "com.mycompany.") */
  readonly namespace: string
  /** Output directory path */
  readonly outputPath: string
  /** Axiom schemas to include */
  readonly schemas: readonly ObjectSchema<string, FieldRecord>[]
  /** npm package name (default: derived from namespace) */
  readonly packageName?: string
  /** Package version (default: "1.0.0") */
  readonly version?: string
  /** Package author */
  readonly author?: string
  /** Package description */
  readonly description?: string
  /** Include links in ontology (default: true) */
  readonly includeLinks?: boolean
}

/**
 * Configuration for generating just the ontology module (no package scaffolding)
 */
export interface OntologyModuleConfig {
  /** Foundry namespace */
  readonly namespace: string
  /** Axiom schemas */
  readonly schemas: readonly ObjectSchema<string, FieldRecord>[]
  /** Include links (default: true) */
  readonly includeLinks?: boolean
}

/**
 * Generated ontology module with file contents
 */
export interface OntologyModule {
  /** Map of file paths to contents */
  readonly files: ReadonlyMap<string, string>
  /** Main entrypoint file path */
  readonly entrypoint: string
}

// =============================================================================
// Error Types
// =============================================================================

export class ScaffoldError {
  readonly _tag = "ScaffoldError"
  constructor(
    readonly message: string,
    readonly cause?: unknown
  ) {}
}

// =============================================================================
// Template Generators
// =============================================================================

const generatePackageJson = (config: OntologyAsCodeConfig): string => {
  const name =
    config.packageName ??
    `@${config.namespace.replace(/\.$/, "").replace(/\./g, "-")}/ontology`

  return JSON.stringify(
    {
      name,
      version: config.version ?? "1.0.0",
      type: "module",
      description:
        config.description ?? `Ontology as Code for ${config.namespace}`,
      ...(config.author && { author: config.author }),
      scripts: {
        build: "tsx scripts/build.ts",
        validate: "tsc --noEmit",
        typecheck: "tsc --noEmit",
      },
      dependencies: {
        "@osdk/maker": "^2.0.0",
      },
      devDependencies: {
        typescript: "^5.0.0",
        tsx: "^4.0.0",
        "@types/node": "^20.0.0",
      },
    },
    null,
    2
  )
}

const generateTsConfig = (): string =>
  JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "ESNext",
        moduleResolution: "bundler",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        declaration: true,
        outDir: "./dist",
        rootDir: ".",
      },
      include: ["ontology/**/*", "scripts/**/*"],
      exclude: ["node_modules", "dist"],
    },
    null,
    2
  )

const generateReadme = (config: OntologyAsCodeConfig): string => `# ${
  config.namespace
} Ontology

Ontology as Code repository generated by Axiom Schema Compiler.

## Setup

\`\`\`bash
npm install
\`\`\`

## Validate

\`\`\`bash
npm run validate
\`\`\`

## Build

\`\`\`bash
npm run build
\`\`\`

## Deploy to Foundry

1. **Commit and push** your changes to your Git repository
2. **Create a Git tag** for the version you want to deploy:
   \`\`\`bash
   git tag v${config.version ?? "1.0.0"}
   git push origin v${config.version ?? "1.0.0"}
   \`\`\`
3. **Marketplace Installation**:
   - Navigate to Foundry Marketplace
   - Find your published ontology product
   - Click "Install" to sync to your Foundry instance

## Schema Objects

${config.schemas.map((s) => `- **${s._name}**: ${s._metadata?.description ?? "No description"}`).join("\n")}

## Architecture

\`\`\`
ontology/
├── index.ts          # Main entrypoint
├── objects/          # Object type definitions
│   ├── index.ts      # Barrel export
│   └── *.ts          # Individual object types
└── links/            # Link definitions
    ├── index.ts      # Barrel export
    └── *.ts          # Individual links
\`\`\`

## Generated by

Axiom Schema Compiler - Canonical schema DSL for Palantir OSDK
`

const generateBuildScript = (config: OntologyAsCodeConfig): string => `/**
 * Build script for Ontology as Code
 *
 * Executes @osdk/maker to generate Foundry-compatible ontology output.
 */

import { defineOntology } from "@osdk/maker";
import { ontologyDefinition } from "../ontology/index.js";

const namespace = "${config.namespace}";
const outputPath = "./dist/ontology";

console.log(\`Building ontology for namespace: \${namespace}\`);

await defineOntology(namespace, ontologyDefinition, outputPath);

console.log(\`Ontology built successfully to: \${outputPath}\`);
`

// =============================================================================
// Object Code Generators
// =============================================================================

const generateObjectFile = (def: OSDKObjectDefinition): string => {
  const propsCode = globalThis.Object.entries(def.properties)
    .map(([key, prop]) => {
      const typeStr =
        typeof prop.type === "object"
          ? JSON.stringify(prop.type)
          : `"${prop.type}"`

      const extras: string[] = []
      if (prop.displayName) extras.push(`displayName: "${prop.displayName}"`)
      if (prop.description) extras.push(`description: "${prop.description}"`)
      if (prop.nullable) extras.push(`nullable: true`)
      if (prop.array) extras.push(`array: true`)

      if (extras.length > 0) {
        return `    "${key}": { type: ${typeStr}, ${extras.join(", ")} }`
      }
      return `    "${key}": { type: ${typeStr} }`
    })
    .join(",\n")

  return `/**
 * ${def.apiName} Object Type
 * ${def.description ?? ""}
 */

import { defineObject } from "@osdk/maker";

export const ${def.apiName} = defineObject({
  apiName: "${def.apiName}",
  displayName: "${def.displayName}",
  pluralDisplayName: "${def.pluralDisplayName}",${def.description ? `\n  description: "${def.description}",` : ""}
  primaryKeyPropertyApiName: "${def.primaryKeyPropertyApiName}",
  titlePropertyApiName: "${def.titlePropertyApiName}",
  properties: {
${propsCode}
  },
});
`
}

const generateObjectsIndex = (defs: OSDKObjectDefinition[]): string => {
  const exports = defs
    .map((def) => `export { ${def.apiName} } from "./${def.apiName}.js";`)
    .join("\n")

  return `/**
 * Object Type Exports
 */

${exports}
`
}

// =============================================================================
// Link Code Generators
// =============================================================================

interface LinkInfo {
  apiName: string
  sourceName: string
  targetName: string
  cardinality: LinkCardinality
  foreignKeyProperty?: string
}

const generateLinkFile = (link: LinkInfo): string => {
  const { apiName, sourceName, targetName, cardinality, foreignKeyProperty } =
    link

  let linkConfig = ""
  if (cardinality === "many-to-one") {
    linkConfig = `  one: {
    object: ${targetName},
    metadata: {
      apiName: "${targetName.toLowerCase()}",
      displayName: "${targetName}",
      pluralDisplayName: "${targetName}s",
    },
  },
  toMany: {
    object: ${sourceName},
    metadata: {
      apiName: "${sourceName.toLowerCase()}s",
      displayName: "${sourceName}",
      pluralDisplayName: "${sourceName}s",
    },
  },${foreignKeyProperty ? `\n  manyForeignKeyProperty: "${foreignKeyProperty}",` : ""}`
  } else if (cardinality === "one-to-many") {
    linkConfig = `  one: {
    object: ${sourceName},
    metadata: {
      apiName: "${sourceName.toLowerCase()}",
      displayName: "${sourceName}",
      pluralDisplayName: "${sourceName}s",
    },
  },
  toMany: {
    object: ${targetName},
    metadata: {
      apiName: "${targetName.toLowerCase()}s",
      displayName: "${targetName}",
      pluralDisplayName: "${targetName}s",
    },
  },`
  } else if (cardinality === "one-to-one") {
    linkConfig = `  one: {
    object: ${sourceName},
    metadata: {
      apiName: "${sourceName.toLowerCase()}",
      displayName: "${sourceName}",
      pluralDisplayName: "${sourceName}s",
    },
  },
  toOne: {
    object: ${targetName},
    metadata: {
      apiName: "${targetName.toLowerCase()}",
      displayName: "${targetName}",
      pluralDisplayName: "${targetName}s",
    },
  },`
  } else {
    // many-to-many
    linkConfig = `  toMany: {
    object: ${targetName},
    metadata: {
      apiName: "${targetName.toLowerCase()}s",
      displayName: "${targetName}",
      pluralDisplayName: "${targetName}s",
    },
  },`
  }

  return `/**
 * ${apiName} Link
 * ${sourceName} → ${targetName} (${cardinality})
 */

import { defineLink } from "@osdk/maker";
import { ${sourceName} } from "../objects/${sourceName}.js";
import { ${targetName} } from "../objects/${targetName}.js";

export const ${apiName} = defineLink({
  apiName: "${apiName}",
${linkConfig}
});
`
}

const generateLinksIndex = (links: LinkInfo[]): string => {
  if (links.length === 0) {
    return `/**
 * Link Type Exports
 */

// No links defined
export {};
`
  }

  const exports = links
    .map((link) => `export { ${link.apiName} } from "./${link.apiName}.js";`)
    .join("\n")

  return `/**
 * Link Type Exports
 */

${exports}
`
}

// =============================================================================
// Main Entrypoint Generator
// =============================================================================

const generateOntologyIndex = (
  defs: OSDKObjectDefinition[],
  links: LinkInfo[]
): string => {
  const objectImports = defs
    .map((def) => `import { ${def.apiName} } from "./objects/${def.apiName}.js";`)
    .join("\n")

  const linkImports =
    links.length > 0
      ? links
          .map(
            (link) =>
              `import { ${link.apiName} } from "./links/${link.apiName}.js";`
          )
          .join("\n")
      : ""

  const objectReExports = defs.map((def) => def.apiName).join(", ")
  const linkReExports =
    links.length > 0 ? links.map((link) => link.apiName).join(", ") : ""

  return `/**
 * Ontology Definition
 *
 * Main entrypoint for Ontology as Code.
 * This file is used by the build script to generate the Foundry ontology.
 */

${objectImports}
${linkImports ? `\n${linkImports}` : ""}

// Re-export all definitions
export { ${objectReExports} };
${linkReExports ? `export { ${linkReExports} };` : ""}

/**
 * Ontology definition function for @osdk/maker
 *
 * This is called by defineOntology() in the build script.
 */
export const ontologyDefinition = async () => {
  // Objects are auto-registered when imported
  // Links are auto-registered when imported
  console.log("Ontology loaded:");
  console.log("  Objects: ${defs.map((d) => d.apiName).join(", ")}");
  ${links.length > 0 ? `console.log("  Links: ${links.map((l) => l.apiName).join(", ")}");` : ""}
};
`
}

// =============================================================================
// Module Generator
// =============================================================================

/**
 * Generate the ontology module files without package scaffolding.
 *
 * Returns a map of file paths to contents.
 */
export const generateOntologyModule = (
  config: OntologyModuleConfig
): Effect.Effect<OntologyModule, CompileError> => {
  const { namespace, schemas, includeLinks = true } = config

  // Compile all schemas to OSDK definitions
  return Effect.flatMap(Effect.all(schemas.map(compileToOSDK)), (defs) => {
    const files = new Map<string, string>()

    // Generate object files
    for (const def of defs) {
      files.set(`ontology/objects/${def.apiName}.ts`, generateObjectFile(def))
    }

    // Generate objects index
    files.set("ontology/objects/index.ts", generateObjectsIndex(defs))

    // Extract and generate links if requested
    if (!includeLinks) {
      files.set("ontology/links/index.ts", generateLinksIndex([]))
      files.set(
        "ontology/index.ts",
        generateOntologyIndex(defs, [])
      )
      return Effect.succeed({
        files,
        entrypoint: "ontology/index.ts",
      })
    }

    // Build object definitions map for link extraction
    const objectDefMap = new Map(defs.map((d) => [d.apiName, d]))

    // Extract links from all schemas
    const linkInfos: LinkInfo[] = []
    for (const schema of schemas) {
      const fields = schema._fields as Record<string, Record<string, unknown>>

      for (const [key, field] of globalThis.Object.entries(fields)) {
        if (!isLink(field)) continue

        const linkField = field as unknown as LinkType<unknown, LinkCardinality>
        const targetSchema = linkField._target() as ObjectSchema<
          string,
          FieldRecord
        >
        const cardinality = linkField._cardinality

        linkInfos.push({
          apiName: `${schema._name}To${targetSchema._name}`,
          sourceName: schema._name,
          targetName: targetSchema._name,
          cardinality,
          foreignKeyProperty:
            cardinality === "many-to-one" ? key : undefined,
        })
      }
    }

    // Generate link files
    for (const link of linkInfos) {
      files.set(`ontology/links/${link.apiName}.ts`, generateLinkFile(link))
    }

    // Generate links index
    files.set("ontology/links/index.ts", generateLinksIndex(linkInfos))

    // Generate main index
    files.set("ontology/index.ts", generateOntologyIndex(defs, linkInfos))

    return Effect.succeed({
      files,
      entrypoint: "ontology/index.ts",
    })
  })
}

// =============================================================================
// Repository Scaffolder
// =============================================================================

/**
 * Scaffold a complete Ontology as Code repository.
 *
 * Creates the following structure:
 * - package.json with @osdk/maker dependencies
 * - tsconfig.json for TypeScript
 * - README.md with deployment instructions
 * - ontology/ directory with object and link definitions
 * - scripts/ directory with build script
 *
 * @example
 * ```ts
 * await Effect.runPromise(
 *   scaffoldOntologyRepo({
 *     namespace: "com.mycompany.",
 *     outputPath: "./my-ontology",
 *     schemas: [Department, Employee],
 *   })
 * )
 * ```
 */
export const scaffoldOntologyRepo = (
  config: OntologyAsCodeConfig
): Effect.Effect<void, CompileError | ScaffoldError> => {
  const { outputPath, includeLinks = true } = config

  return Effect.flatMap(
    generateOntologyModule({
      namespace: config.namespace,
      schemas: config.schemas,
      includeLinks,
    }),
    (module) =>
      Effect.try({
        try: () => {
          // Create directory structure
          const dirs = [
            outputPath,
            join(outputPath, "ontology"),
            join(outputPath, "ontology", "objects"),
            join(outputPath, "ontology", "links"),
            join(outputPath, "scripts"),
          ]

          for (const dir of dirs) {
            mkdirSync(dir, { recursive: true })
          }

          // Write package files
          writeFileSync(
            join(outputPath, "package.json"),
            generatePackageJson(config)
          )
          writeFileSync(join(outputPath, "tsconfig.json"), generateTsConfig())
          writeFileSync(join(outputPath, "README.md"), generateReadme(config))

          // Write build script
          writeFileSync(
            join(outputPath, "scripts", "build.ts"),
            generateBuildScript(config)
          )

          // Write ontology module files
          Array.from(module.files.entries()).forEach(([filePath, content]) => {
            writeFileSync(join(outputPath, filePath), content)
          })

          console.log(`Ontology as Code repository scaffolded at: ${outputPath}`)
          console.log("Next steps:")
          console.log("  1. cd " + outputPath)
          console.log("  2. npm install")
          console.log("  3. npm run validate")
          console.log("  4. npm run build")
          console.log("  5. git init && git add . && git commit -m 'Initial ontology'")
          console.log("  6. git tag v" + (config.version ?? "1.0.0"))
        },
        catch: (e) =>
          new ScaffoldError(
            `Failed to scaffold repository: ${e}`,
            e
          ),
      })
  )
}

/**
 * Preview the files that would be generated without writing to disk.
 *
 * Useful for debugging or generating to alternative outputs.
 */
export const previewOntologyRepo = (
  config: OntologyAsCodeConfig
): Effect.Effect<ReadonlyMap<string, string>, CompileError> => {
  return Effect.map(
    generateOntologyModule({
      namespace: config.namespace,
      schemas: config.schemas,
      includeLinks: config.includeLinks ?? true,
    }),
    (module) => {
      const allFiles = new Map<string, string>()

      // Add package files
      allFiles.set("package.json", generatePackageJson(config))
      allFiles.set("tsconfig.json", generateTsConfig())
      allFiles.set("README.md", generateReadme(config))
      allFiles.set("scripts/build.ts", generateBuildScript(config))

      // Add ontology module files
      Array.from(module.files.entries()).forEach(([path, content]) => {
        allFiles.set(path, content)
      })

      return allFiles
    }
  )
}
