#!/usr/bin/env python3
"""Emit a Muse Transport Integrity metric-pack result.

Input is the first-order summary generated by ``analyze_capture.py``. The script
maps transport/counter/timing fields to ``MuseMetricPackResult`` metrics and
threshold evaluations, then optionally renders the standard Markdown report.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

try:
    from .metric_pack_report import render_markdown
except ImportError:  # Allow `python scripts/muse/transport_integrity_report.py ...`
    from metric_pack_report import render_markdown  # type: ignore

DEFAULT_POLICY_PATH = Path("docs/muse/transport-integrity-thresholds.json")
PACK_ID = "transport-integrity"


class TransportReportError(ValueError):
    """Raised when transport pack result generation fails."""


def load_json_object(path: Path, *, label: str) -> dict[str, Any]:
    try:
        with path.open("r", encoding="utf-8") as file:
            data = json.load(file)
    except json.JSONDecodeError as exc:
        raise TransportReportError(f"{path}:{exc.lineno}: malformed {label} JSON: {exc.msg} at column {exc.colno}") from exc
    except OSError as exc:
        raise TransportReportError(f"{path}: {exc}") from exc
    if not isinstance(data, dict):
        raise TransportReportError(f"{path}: expected {label} JSON object, got {type(data).__name__}")
    return data


def load_policy_array(path: Path) -> list[dict[str, Any]]:
    try:
        with path.open("r", encoding="utf-8") as file:
            data = json.load(file)
    except json.JSONDecodeError as exc:
        raise TransportReportError(f"{path}:{exc.lineno}: malformed policy JSON: {exc.msg} at column {exc.colno}") from exc
    except OSError as exc:
        raise TransportReportError(f"{path}: {exc}") from exc
    if not isinstance(data, list) or not all(isinstance(item, dict) for item in data):
        raise TransportReportError(f"{path}: expected array of policy objects")
    return data


def metric(key: str, value: Any, *, scope: str = "session", unit: str | None = None, **extra: Any) -> dict[str, Any]:
    item: dict[str, Any] = {"key": key, "value": value, "scope": scope}
    if unit is not None:
        item["unit"] = unit
    for field, field_value in extra.items():
        if field_value is not None:
            item[field] = field_value
    return item


def nested_get(data: Mapping[str, Any], dotted_key: str) -> Any:
    current: Any = data
    for part in dotted_key.split("."):
        if isinstance(current, Mapping) and part in current:
            current = current[part]
        else:
            return None
    return current


def compare_value(observed: Any, comparator: str, threshold: Any) -> bool:
    if comparator == "eq":
        return observed == threshold
    if comparator == "neq":
        return observed != threshold
    if comparator == "present":
        return observed is not None
    if comparator == "absent":
        return observed is None
    if observed is None:
        return False
    if comparator in {"lt", "lte", "gt", "gte"}:
        if not isinstance(observed, (int, float)) or isinstance(observed, bool):
            return False
        if not isinstance(threshold, (int, float)) or isinstance(threshold, bool):
            return False
        if comparator == "lt":
            return observed < threshold
        if comparator == "lte":
            return observed <= threshold
        if comparator == "gt":
            return observed > threshold
        return observed >= threshold
    if comparator in {"between_inclusive", "outside_inclusive"}:
        if not isinstance(observed, (int, float)) or isinstance(observed, bool):
            return False
        if not isinstance(threshold, list) or len(threshold) != 2:
            return False
        lo, hi = threshold
        if not isinstance(lo, (int, float)) or not isinstance(hi, (int, float)):
            return False
        inside = lo <= observed <= hi
        return inside if comparator == "between_inclusive" else not inside
    return False


def status_for_policy(policy: Mapping[str, Any], passed: bool) -> str:
    if passed:
        return "pass"
    kind = policy.get("kind")
    severity = policy.get("severity")
    if kind == "soft_warning" or severity == "warn":
        return "warn"
    return "fail"


def evaluation_from_policy(policy: Mapping[str, Any], observed: Any, *, metric_key: str | None = None, stream_key: str | None = None) -> dict[str, Any]:
    comparator = str(policy.get("comparator", "present"))
    threshold = policy.get("threshold")
    passed = compare_value(observed, comparator, threshold)
    status = status_for_policy(policy, passed)
    description = str(policy.get("description", ""))
    if stream_key is not None:
        description = f"{stream_key}: {description}"
    item: dict[str, Any] = {
        "metricKey": metric_key or str(policy.get("metricKey", "")),
        "comparator": comparator,
        "status": status,
        "severity": policy.get("severity", "info"),
        "policyId": policy.get("policyId"),
        "description": description,
    }
    if threshold is not None:
        item["threshold"] = threshold
    if observed is not None:
        item["observed"] = observed
    return item


def applies_to_stream(policy: Mapping[str, Any], stream: Mapping[str, Any]) -> bool:
    applies = policy.get("appliesWhen")
    if not isinstance(applies, Mapping):
        return True
    for key, expected in applies.items():
        actual = stream.get(key)
        if isinstance(expected, list):
            if actual not in expected:
                return False
        elif actual != expected:
            return False
    return True


def detect_no_contact(summary: Mapping[str, Any]) -> bool:
    manifest = summary.get("manifest")
    if not isinstance(manifest, Mapping):
        return False
    haystack: list[str] = []
    for key in ("taskName", "purpose", "interpretationBoundary"):
        value = manifest.get(key)
        if isinstance(value, str):
            haystack.append(value)
    for section_name in ("participant", "environment"):
        section = manifest.get(section_name)
        if isinstance(section, Mapping):
            for value in section.values():
                if isinstance(value, str):
                    haystack.append(value)
    text = " ".join(haystack).lower()
    return any(phrase in text for phrase in ("no-contact", "no contact", "no brain", "not connected to brain", "not worn", "device-only", "device only"))


def timestamp_regressions_total(summary: Mapping[str, Any]) -> int | None:
    transport = summary.get("transport")
    if not isinstance(transport, Mapping):
        return None
    total = 0
    for key in ("eventTimestampRegressions", "sampleTimestampRegressions", "summaryTimestampRegressions"):
        value = transport.get(key)
        if isinstance(value, int):
            total += value
    streams = summary.get("streams")
    if isinstance(streams, Mapping):
        for stream in streams.values():
            if isinstance(stream, Mapping) and isinstance(stream.get("timestampRegressions"), int):
                total += int(stream["timestampRegressions"])
    return total


def capture_lifecycle_complete(summary: Mapping[str, Any]) -> bool | None:
    transport = summary.get("transport")
    if not isinstance(transport, Mapping):
        return None
    return transport.get("captureStartEvents") == 1 and transport.get("captureStopEvents") == 1


def build_metrics(summary: Mapping[str, Any], *, summary_path: Path) -> list[dict[str, Any]]:
    transport = summary.get("transport") if isinstance(summary.get("transport"), Mapping) else {}
    totals = summary.get("totals") if isinstance(summary.get("totals"), Mapping) else {}
    streams = summary.get("streams") if isinstance(summary.get("streams"), Mapping) else {}
    metrics: list[dict[str, Any]] = [
        metric("totals.events", totals.get("events"), unit="count", sourcePath=str(summary_path)),
        metric("totals.sampleEvents", totals.get("sampleEvents"), unit="count", sourcePath=str(summary_path)),
        metric("totals.malformedEvents", totals.get("malformedEvents"), unit="count", sourcePath=str(summary_path)),
        metric("transport.decodeErrorsLast", transport.get("decodeErrorsLast"), unit="count", sourcePath=str(summary_path)),
        metric("transport.packetsDroppedLast", transport.get("packetsDroppedLast"), unit="count", sourcePath=str(summary_path)),
        metric("transport.summaryCadencePresent", transport.get("summaryCadencePresent"), sourcePath=str(summary_path)),
        metric("transport.captureLifecycleComplete", capture_lifecycle_complete(summary), sourcePath=str(summary_path)),
        metric("transport.timestampRegressionsTotal", timestamp_regressions_total(summary), unit="count", sourcePath=str(summary_path)),
        metric("transport.sampleCoverageRatio", transport.get("sampleCoverageRatio"), sourcePath=str(summary_path)),
        metric("transport.sampleEventRateHzObserved", transport.get("sampleEventRateHzObserved"), unit="Hz", sourcePath=str(summary_path)),
        metric("transport.interSampleEventDeltaSec.p99Sec", nested_get(transport, "interSampleEventDeltaSec.p99Sec"), unit="s", sourcePath=str(summary_path)),
        metric("transport.interSummaryDeltaSec.p95Sec", nested_get(transport, "interSummaryDeltaSec.p95Sec"), unit="s", sourcePath=str(summary_path)),
        metric("transport.queueFillFractionMax", transport.get("queueFillFractionMax"), sourcePath=str(summary_path)),
    ]
    for stream_key, stream in sorted(streams.items()):
        if not isinstance(stream, Mapping):
            continue
        sensor = str(stream.get("sensor", "unknown"))
        channel = str(stream.get("channel", stream_key))
        metrics.extend([
            metric("stream.eventRateHzObserved", stream.get("eventRateHzObserved"), scope="stream", unit="Hz", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
            metric("stream.sequenceGaps", stream.get("sequenceGaps"), scope="stream", unit="count", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
            metric("stream.missingPacketsEstimate", stream.get("missingPacketsEstimate"), scope="stream", unit="count", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
            metric("stream.duplicateSequences", stream.get("duplicateSequences"), scope="stream", unit="count", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
            metric("stream.outOfOrderSequences", stream.get("outOfOrderSequences"), scope="stream", unit="count", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
            metric("stream.interEventDeltaSec.p99Sec", nested_get(stream, "interEventDeltaSec.p99Sec"), scope="stream", unit="s", channel=channel, notes=stream_key, sourcePath=str(summary_path)),
        ])
        if sensor == "telemetry" and isinstance(stream.get("duplicateSequences"), int) and stream["duplicateSequences"] > 0:
            metrics.append(metric("stream.telemetryDuplicateSequencesDisclosed", True, scope="stream", channel=channel, notes=stream_key, sourcePath=str(summary_path)))
    return metrics


def build_evaluations(summary: Mapping[str, Any], policies: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]:
    transport = summary.get("transport") if isinstance(summary.get("transport"), Mapping) else {}
    streams = summary.get("streams") if isinstance(summary.get("streams"), Mapping) else {}
    synthetic_summary = dict(summary)
    synthetic_summary["transport"] = dict(transport)
    synthetic_summary["transport"]["captureLifecycleComplete"] = capture_lifecycle_complete(summary)
    synthetic_summary["transport"]["timestampRegressionsTotal"] = timestamp_regressions_total(summary)

    evaluations: list[dict[str, Any]] = []
    for policy in policies:
        metric_key = str(policy.get("metricKey", ""))
        if metric_key.startswith("stream."):
            for stream_key, stream in sorted(streams.items()):
                if not isinstance(stream, Mapping) or not applies_to_stream(policy, stream):
                    continue
                observed = nested_get(stream, metric_key.removeprefix("stream."))
                evaluations.append(evaluation_from_policy(policy, observed, stream_key=str(stream_key)))
        else:
            observed = nested_get(synthetic_summary, metric_key)
            evaluations.append(evaluation_from_policy(policy, observed))
    return evaluations


def build_caveats(summary: Mapping[str, Any]) -> list[dict[str, Any]]:
    caveats: list[dict[str, Any]] = [
        {
            "severity": "info",
            "message": "Transport Integrity validates capture/decoder/timing plumbing only. It does not establish contact, EEG quality, physiology, alpha response, or ML readiness.",
            "blocksClaim": True,
            "source": "docs/muse/transport-integrity-thresholds.md",
        }
    ]
    if detect_no_contact(summary):
        caveats.append({
            "severity": "critical",
            "message": "Manifest indicates a no-contact/device-only session. Transport checks may pass, but EEG, artifact, alpha, physiology, cognitive, clinical, and ML claims remain barred.",
            "blocksClaim": True,
            "source": "manifest.interpretationBoundary",
        })
    streams = summary.get("streams")
    if isinstance(streams, Mapping):
        for stream_key, stream in sorted(streams.items()):
            if not isinstance(stream, Mapping):
                continue
            if stream.get("sensor") == "telemetry" and isinstance(stream.get("duplicateSequences"), int) and stream["duplicateSequences"] > 0:
                caveats.append({
                    "severity": "warn",
                    "message": f"{stream_key} reports duplicate sequence values; telemetry duplicate behavior is disclosed but does not fail packet-loss gates until telemetry sequence semantics are proven equivalent to EEG/IMU counters.",
                    "blocksClaim": False,
                    "source": "docs/muse/transport-integrity-thresholds.md#telemetry-duplicate-sequence-exception",
                })
    return caveats


def aggregate_status(evaluations: Sequence[Mapping[str, Any]], caveats: Sequence[Mapping[str, Any]]) -> str:
    if any(evaluation.get("status") == "fail" for evaluation in evaluations):
        return "fail"
    if any(evaluation.get("status") == "warn" for evaluation in evaluations):
        return "warn"
    if any(caveat.get("severity") in {"warn", "critical"} for caveat in caveats):
        return "warn"
    return "pass"


def build_result(summary: Mapping[str, Any], policies: Sequence[Mapping[str, Any]], *, summary_path: Path, policy_path: Path) -> dict[str, Any]:
    manifest = summary.get("manifest") if isinstance(summary.get("manifest"), Mapping) else {}
    files = summary.get("files") if isinstance(summary.get("files"), list) else []
    metrics = build_metrics(summary, summary_path=summary_path)
    evaluations = build_evaluations(summary, policies)
    caveats = build_caveats(summary)
    result: dict[str, Any] = {
        "type": "muse.metric_pack_result",
        "schemaVersion": "muse-metric-pack-result/v1",
        "packId": PACK_ID,
        "status": aggregate_status(evaluations, caveats),
        "generatedAt": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
        "interpretationBoundary": "Transport Integrity validates Muse BLE/capture/decoder/timing preservation only; it does not authorize contact, EEG quality, physiology, alpha, cognitive, clinical, or ML claims.",
        "upstreamDependencies": [],
        "metrics": metrics,
        "thresholdEvaluations": evaluations,
        "evidence": [
            {"role": "summary_json", "path": str(summary_path), "mediaType": "application/json", "notes": "First-order summary with transport timing section."},
            {"role": "other", "path": str(policy_path), "mediaType": "application/json", "notes": "Transport Integrity threshold policy set."},
        ],
        "caveats": caveats,
        "recommendations": [
            "Proceed to Contact/Fit only if Protocol Compliance and Transport Integrity caveats allow the intended claim.",
            "Do not treat transport pass/warn as EEG quality evidence.",
        ],
        "metadata": {"generator": "scripts/muse/transport_integrity_report.py", "policyCount": len(policies)},
    }
    if isinstance(manifest.get("sessionId"), str):
        result["sessionId"] = manifest["sessionId"]
    if isinstance(summary.get("manifestPath"), str):
        result["manifestPath"] = summary["manifestPath"]
        result["evidence"].append({"role": "manifest", "path": summary["manifestPath"], "mediaType": "application/json"})
    for file_path in files:
        if isinstance(file_path, str):
            result["evidence"].append({"role": "raw_input", "path": file_path, "mediaType": "application/x-ndjson"})
    return result


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Emit a Muse Transport Integrity metric-pack result from a first-order summary JSON.")
    parser.add_argument("summary", type=Path, help="First-order summary JSON from scripts/muse/analyze_capture.py")
    parser.add_argument("--policies", type=Path, default=DEFAULT_POLICY_PATH, help="Transport threshold policy JSON file.")
    parser.add_argument("--output", type=Path, default=None, help="Output MuseMetricPackResult JSON path. Defaults to stdout.")
    parser.add_argument("--report", type=Path, default=None, help="Optional Markdown report path rendered from the result.")
    return parser


def main(argv: Iterable[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        summary = load_json_object(args.summary, label="first-order summary")
        policies = load_policy_array(args.policies)
        result = build_result(summary, policies, summary_path=args.summary, policy_path=args.policies)
        if args.output is None:
            print(json.dumps(result, indent=2, sort_keys=True))
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        if args.report is not None:
            args.report.parent.mkdir(parents=True, exist_ok=True)
            args.report.write_text(render_markdown(result), encoding="utf-8")
        return 1 if result.get("status") == "fail" else 0
    except (TransportReportError, OSError) as exc:
        print(f"muse transport report error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
