/**
 * AreaState Service
 *
 * Effect.Service for Area state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * ISA-95 Hierarchy: Enterprise -> Site -> **Area** -> Plant/Line -> Machine -> Sensor
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { AreaId, SiteId, EnterpriseId } from '../schemas/identifiers'
import { Area, CreateAreaParams, makeAreaId } from '../schemas/assets/area'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions, TimeRangeFilter } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let areaCounter = 0

/** Generate a unique area ID for in-memory testing */
const generateAreaId = (): AreaId => makeAreaId(`gen-${Date.now()}-${++areaCounter}`)

// =============================================================================
// Filter & Error Types
// =============================================================================

/** Filter for listing areas */
export interface AreaFilter extends PaginationOptions, TimeRangeFilter {
  /** Filter by parent site */
  readonly siteId?: SiteId
  /** Filter by parent enterprise */
  readonly enterpriseId?: EnterpriseId
  /** Filter by operational status */
  readonly status?: string
  /** Filter by area type */
  readonly areaType?: string
  /** Filter by building */
  readonly building?: string
}

/** Area state not found error */
export class AreaStateNotFoundError {
  readonly _tag = 'AreaStateNotFoundError'
  constructor(readonly areaId: AreaId) {}
}

// =============================================================================
// Service Shape Interface
// =============================================================================

/**
 * Area State Service Shape
 *
 * Contract for area state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface AreaStateShape {
  /** Create a new area (ID generated by implementation) */
  readonly create: (params: CreateAreaParams) => Effect.Effect<Area>

  /** Get area by ID */
  readonly get: (id: AreaId) => Effect.Effect<Area, AreaStateNotFoundError>

  /** Set/update area state (upsert) - use for updates, not creates */
  readonly set: (area: Area) => Effect.Effect<void>

  /** List areas matching filter */
  readonly list: (filter: AreaFilter) => Effect.Effect<readonly Area[]>

  /** Delete area by ID */
  readonly delete: (id: AreaId) => Effect.Effect<boolean>

  /** Check if area exists */
  readonly exists: (id: AreaId) => Effect.Effect<boolean>

  /** Count areas matching filter */
  readonly count: (filter: AreaFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * AreaState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* AreaState
 *   const area = yield* state.get(areaId)
 * })
 * ```
 */
export class AreaState extends Context.Tag('iiot/AreaState')<
  AreaState,
  AreaStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory area state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const AreaStateInMemory: Layer.Layer<AreaState> = Layer.effect(
  AreaState,
  Ref.make(new Map<AreaId, Area>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (area: Area, filter: AreaFilter): boolean => {
        if (filter.siteId && area.siteId !== filter.siteId) return false
        if (filter.enterpriseId && area.enterpriseId !== filter.enterpriseId) return false
        if (filter.status && area.status !== filter.status) return false
        if (filter.areaType) {
          const areaType = Option.getOrNull(area.areaType)
          if (areaType !== filter.areaType) return false
        }
        if (filter.building) {
          const building = Option.getOrNull(area.building)
          if (building !== filter.building) return false
        }
        if (filter.since) {
          const sinceMs = filter.since.getTime()
          const areaMs = Number(area.createdAt.epochMillis)
          if (areaMs < sinceMs) return false
        }
        if (filter.until) {
          const untilMs = filter.until.getTime()
          const areaMs = Number(area.createdAt.epochMillis)
          if (areaMs > untilMs) return false
        }
        return true
      }

      return {
        create: (params: CreateAreaParams) =>
          Effect.gen(function* () {
            const id = generateAreaId()
            const now = yield* DateTime.now

            // Build hierarchy path from parent references
            // For in-memory, we construct a simple path
            const hierarchyPath = HierarchyPath.make({
              segments: [
                PathSegment.make({ level: 'site', id: params.siteId }),
                PathSegment.make({ level: 'area', id }),
              ],
              materialized: `${params.siteId}/${id}`,
            })

            const area = new Area({
              id,
              name: params.name,
              status: Option.getOrElse(params.status, () => 'active' as const),
              siteId: params.siteId,
              // For in-memory, we need enterpriseId - use a placeholder if not derivable
              // In production, this would be looked up from the Site
              enterpriseId: 'ENT-default' as EnterpriseId,
              areaType: params.areaType !== undefined ? Option.some(params.areaType) : Option.none(),
              building: params.building !== undefined ? Option.some(params.building) : Option.none(),
              floor: params.floor !== undefined ? Option.some(params.floor) : Option.none(),
              zone: params.zone !== undefined ? Option.some(params.zone) : Option.none(),
              description: params.description !== undefined ? Option.some(params.description) : Option.none(),
              createdAt: now,
              updatedAt: Option.none(),
              metadata: params.metadata ?? {},
              hierarchyPath,
              location: Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, area)
              return newMap
            })
            return area
          }),

        get: (id: AreaId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const area = map.get(id)
              if (!area) {
                return Effect.fail(new AreaStateNotFoundError(id))
              }
              return Effect.succeed(area)
            })
          ),

        set: (area: Area) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(area.id, area)
            return newMap
          }),

        list: (filter: AreaFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let areas = Array.from(map.values()).filter((a) =>
                matchesFilter(a, filter)
              )

              // Sort by createdAt descending
              areas.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                areas = areas.slice(filter.offset)
              }
              if (filter.limit) {
                areas = areas.slice(0, filter.limit)
              }

              return areas
            })
          ),

        delete: (id: AreaId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: AreaId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: AreaFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((a) => matchesFilter(a, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Factory
// =============================================================================

/**
 * Factory to create SQL-backed area state from a repository.
 *
 * Bridges the state interface to the repository pattern.
 * For the full SQL implementation, see AreaRepo.
 */
export const makeAreaStateSql = (repo: {
  findById: (id: AreaId) => Effect.Effect<Option.Option<Area>, unknown>
  findAll: (filter: AreaFilter) => Effect.Effect<readonly Area[], unknown>
  insert: (area: Area) => Effect.Effect<Area, unknown>
  update: (area: Partial<Area> & { id: AreaId }) => Effect.Effect<Area, unknown>
  delete: (id: AreaId) => Effect.Effect<boolean, unknown>
  /** Insert with DB-generated ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateAreaParams) => Effect.Effect<Area, unknown>
}): AreaStateShape => ({
  create: (params: CreateAreaParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(Effect.orDie)
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = generateAreaId()
          const now = yield* DateTime.now

          // Build hierarchy path from parent references
          const hierarchyPath = HierarchyPath.make({
            segments: [
              PathSegment.make({ level: 'site', id: params.siteId }),
              PathSegment.make({ level: 'area', id }),
            ],
            materialized: `${params.siteId}/${id}`,
          })

          const area = new Area({
            id,
            name: params.name,
            status: Option.getOrElse(params.status, () => 'active' as const),
            siteId: params.siteId,
            enterpriseId: 'ENT-default' as EnterpriseId,
            areaType: params.areaType !== undefined ? Option.some(params.areaType) : Option.none(),
            building: params.building !== undefined ? Option.some(params.building) : Option.none(),
            floor: params.floor !== undefined ? Option.some(params.floor) : Option.none(),
            zone: params.zone !== undefined ? Option.some(params.zone) : Option.none(),
            description: params.description !== undefined ? Option.some(params.description) : Option.none(),
            createdAt: now,
            updatedAt: Option.none(),
            metadata: params.metadata ?? {},
            hierarchyPath,
            location: Option.none(),
          })
          return yield* repo.insert(area).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new AreaStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new AreaStateNotFoundError(id)))
    ),

  set: (area) =>
    repo.findById(area.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(area as Partial<Area> & { id: AreaId })
          : repo.insert(area)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((areas) => areas.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
