/**
 * DeviceState Service
 *
 * Effect.Service for device state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * Device is ISA-95 Level 0 (Control Module - Actuator).
 * Parent: Machine (via machineId).
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { DeviceId, MachineId } from '../schemas/identifiers'
import { Device, CreateDeviceParams, makeDeviceId, DeviceType } from '../schemas/assets/device'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions, TimeRangeFilter } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let deviceCounter = 0

/** Generate a unique device ID for in-memory testing */
const generateDeviceId = (): DeviceId => `DEV-gen-${Date.now()}-${++deviceCounter}` as DeviceId

// =============================================================================
// Filter Types
// =============================================================================

/** Filter for listing devices */
export interface DeviceFilter extends PaginationOptions, TimeRangeFilter {
  /** Filter by parent machine ID */
  readonly machineId?: MachineId
  /** Filter by device operational status */
  readonly status?: string
  /** Filter by device type (motor, valve, pump, etc.) */
  readonly deviceType?: DeviceType
}

// =============================================================================
// Error Types
// =============================================================================

/** Device state not found error */
export class DeviceStateNotFoundError {
  readonly _tag = 'DeviceStateNotFoundError'
  constructor(readonly deviceId: DeviceId) {}
}

// =============================================================================
// Service Shape
// =============================================================================

/**
 * Device State Service Shape
 *
 * Contract for device state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface DeviceStateShape {
  /** Create a new device (ID generated by implementation) */
  readonly create: (params: CreateDeviceParams) => Effect.Effect<Device>

  /** Get device by ID */
  readonly get: (id: DeviceId) => Effect.Effect<Device, DeviceStateNotFoundError>

  /** Set/update device state (upsert) - use for updates, not creates */
  readonly set: (device: Device) => Effect.Effect<void>

  /** List devices matching filter */
  readonly list: (filter: DeviceFilter) => Effect.Effect<readonly Device[]>

  /** Delete device by ID */
  readonly delete: (id: DeviceId) => Effect.Effect<boolean>

  /** Check if device exists */
  readonly exists: (id: DeviceId) => Effect.Effect<boolean>

  /** Count devices matching filter */
  readonly count: (filter: DeviceFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * DeviceState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* DeviceState
 *   const device = yield* state.get(deviceId)
 * })
 * ```
 */
export class DeviceState extends Context.Tag('iiot/DeviceState')<
  DeviceState,
  DeviceStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory device state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const DeviceStateInMemory: Layer.Layer<DeviceState> = Layer.effect(
  DeviceState,
  Ref.make(new Map<DeviceId, Device>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (device: Device, filter: DeviceFilter): boolean => {
        // Filter by machineId (parent)
        if (filter.machineId) {
          const machineIdOpt = device.machineId
          if (Option.isNone(machineIdOpt) || machineIdOpt.value !== filter.machineId) {
            return false
          }
        }

        // Filter by status
        if (filter.status && device.status !== filter.status) return false

        // Filter by deviceType
        if (filter.deviceType && device.deviceType !== filter.deviceType) return false

        // Filter by time range (using createdAt)
        if (filter.since) {
          const sinceMs = filter.since.getTime()
          const deviceMs = Number(device.createdAt.epochMillis)
          if (deviceMs < sinceMs) return false
        }
        if (filter.until) {
          const untilMs = filter.until.getTime()
          const deviceMs = Number(device.createdAt.epochMillis)
          if (deviceMs > untilMs) return false
        }

        return true
      }

      return {
        create: (params: CreateDeviceParams) =>
          Effect.gen(function* () {
            const id = params.slug
              ? makeDeviceId(params.slug)
              : generateDeviceId()
            const now = yield* DateTime.now

            // Build hierarchy path for device
            // Device's parent is machine, path should include the machine
            const hierarchyPath = HierarchyPath.fromSegments([
              new PathSegment({
                level: 'machine',
                id: params.machineId,
                name: Option.none(),
              }),
              new PathSegment({
                level: 'device',
                id: id,
                name: Option.some(params.name as typeof Schema.NonEmptyString.Type),
              }),
            ])

            const device = new Device({
              id,
              name: params.name,
              status: params.status ?? 'active',
              machineId: Option.some(params.machineId),
              deviceType: params.deviceType,
              controlMode: params.controlMode ? Option.some(params.controlMode) : Option.none(),
              ratedPower: params.ratedPower ? Option.some(params.ratedPower) : Option.none(),
              powerUnit: params.powerUnit ? Option.some(params.powerUnit) : Option.none(),
              lastCommandAt: Option.none(),
              opcUaNodeId: params.opcUaNodeId ? Option.some(params.opcUaNodeId) : Option.none(),
              description: params.description ? Option.some(params.description) : Option.none(),
              createdAt: now,
              updatedAt: Option.none(),
              metadata: params.metadata ?? {},
              hierarchyPath,
              enterpriseId: Option.none(),
              siteId: Option.none(),
              areaId: Option.none(),
              plantId: Option.none(),
              lineId: Option.none(),
              workCellId: Option.none(),
              location: Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, device)
              return newMap
            })

            return device
          }),

        get: (id: DeviceId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const device = map.get(id)
              if (!device) {
                return Effect.fail(new DeviceStateNotFoundError(id))
              }
              return Effect.succeed(device)
            })
          ),

        set: (device: Device) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(device.id, device)
            return newMap
          }),

        list: (filter: DeviceFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let devices = Array.from(map.values()).filter((d) =>
                matchesFilter(d, filter)
              )

              // Sort by createdAt descending (newest first)
              devices.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                devices = devices.slice(filter.offset)
              }
              if (filter.limit) {
                devices = devices.slice(0, filter.limit)
              }

              return devices
            })
          ),

        delete: (id: DeviceId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: DeviceId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: DeviceFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((d) => matchesFilter(d, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Implementation Factory
// =============================================================================

/**
 * SQL-backed device state implementation for production.
 *
 * Uses the existing DeviceRepo for actual SQL operations.
 * This factory bridges the state interface to the repository pattern.
 *
 * For the full SQL implementation, see DeviceRepo.
 */
export const makeDeviceStateSql = (repo: {
  findById: (id: DeviceId) => Effect.Effect<Option.Option<Device>, unknown>
  findAll: (filter: DeviceFilter) => Effect.Effect<readonly Device[], unknown>
  insert: (device: Device) => Effect.Effect<Device, unknown>
  update: (device: Partial<Device> & { id: DeviceId }) => Effect.Effect<Device, unknown>
  delete: (id: DeviceId) => Effect.Effect<boolean, unknown>
  /** Insert with DB-generated ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateDeviceParams) => Effect.Effect<Device, unknown>
}): DeviceStateShape => ({
  create: (params: CreateDeviceParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(
          Effect.orDie // SQL failures are defects
        )
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = params.slug
            ? makeDeviceId(params.slug)
            : generateDeviceId()
          const now = yield* DateTime.now

          // Build hierarchy path for device
          const hierarchyPath = HierarchyPath.fromSegments([
            new PathSegment({
              level: 'machine',
              id: params.machineId,
              name: Option.none(),
            }),
            new PathSegment({
              level: 'device',
              id: id,
              name: Option.some(params.name as typeof Schema.NonEmptyString.Type),
            }),
          ])

          const device = new Device({
            id,
            name: params.name,
            status: params.status ?? 'active',
            machineId: Option.some(params.machineId),
            deviceType: params.deviceType,
            controlMode: params.controlMode ? Option.some(params.controlMode) : Option.none(),
            ratedPower: params.ratedPower ? Option.some(params.ratedPower) : Option.none(),
            powerUnit: params.powerUnit ? Option.some(params.powerUnit) : Option.none(),
            lastCommandAt: Option.none(),
            opcUaNodeId: params.opcUaNodeId ? Option.some(params.opcUaNodeId) : Option.none(),
            description: params.description ? Option.some(params.description) : Option.none(),
            createdAt: now,
            updatedAt: Option.none(),
            metadata: params.metadata ?? {},
            hierarchyPath,
            enterpriseId: Option.none(),
            siteId: Option.none(),
            areaId: Option.none(),
            plantId: Option.none(),
            lineId: Option.none(),
            workCellId: Option.none(),
            location: Option.none(),
          })

          return yield* repo.insert(device).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new DeviceStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new DeviceStateNotFoundError(id)))
    ),

  set: (device) =>
    repo.findById(device.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(device as Partial<Device> & { id: DeviceId })
          : repo.insert(device)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((devices) => devices.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
