/**
 * EnterpriseState Service
 *
 * Effect.Service for Enterprise asset state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * Enterprise is the topmost level of the ISA-95 equipment hierarchy (Level 4).
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { EnterpriseId } from '../schemas/identifiers'
import {
  Enterprise,
  makeEnterpriseId,
  type CreateEnterpriseParams,
} from '../schemas/assets/enterprise'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let enterpriseCounter = 0

/** Generate a unique enterprise ID for in-memory testing */
const generateEnterpriseId = (): EnterpriseId =>
  makeEnterpriseId(`gen-${Date.now()}-${++enterpriseCounter}`)

// =============================================================================
// Filter Interface
// =============================================================================

/**
 * Filter for listing enterprises.
 */
export interface EnterpriseFilter extends PaginationOptions {
  /** Filter by asset status */
  readonly status?: string
  /** Filter by industry sector */
  readonly industry?: string
  /** Search by name (partial match) */
  readonly nameSearch?: string
}

// =============================================================================
// Errors
// =============================================================================

/**
 * Error thrown when an enterprise is not found.
 */
export class EnterpriseStateNotFoundError {
  readonly _tag = 'EnterpriseStateNotFoundError'
  constructor(readonly enterpriseId: EnterpriseId) {}
}

// =============================================================================
// Shape Interface
// =============================================================================

/**
 * EnterpriseState Service Shape
 *
 * Contract for enterprise state storage. Implementations must provide
 * consistent behavior for create/get/set/list/delete operations.
 */
export interface EnterpriseStateShape {
  /** Create a new enterprise (ID generated by implementation) */
  readonly create: (params: CreateEnterpriseParams) => Effect.Effect<Enterprise>

  /** Get enterprise by ID */
  readonly get: (id: EnterpriseId) => Effect.Effect<Enterprise, EnterpriseStateNotFoundError>

  /** Set/update enterprise state (upsert) - use for updates, not creates */
  readonly set: (enterprise: Enterprise) => Effect.Effect<void>

  /** List enterprises matching filter */
  readonly list: (filter: EnterpriseFilter) => Effect.Effect<readonly Enterprise[]>

  /** Delete enterprise by ID */
  readonly delete: (id: EnterpriseId) => Effect.Effect<boolean>

  /** Check if enterprise exists */
  readonly exists: (id: EnterpriseId) => Effect.Effect<boolean>

  /** Count enterprises matching filter */
  readonly count: (filter: EnterpriseFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * EnterpriseState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* EnterpriseState
 *   const enterprise = yield* state.get(enterpriseId)
 * })
 * ```
 */
export class EnterpriseState extends Context.Tag('iiot/EnterpriseState')<
  EnterpriseState,
  EnterpriseStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory enterprise state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const EnterpriseStateInMemory: Layer.Layer<EnterpriseState> = Layer.effect(
  EnterpriseState,
  Ref.make(new Map<EnterpriseId, Enterprise>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (enterprise: Enterprise, filter: EnterpriseFilter): boolean => {
        if (filter.status && enterprise.status !== filter.status) return false
        if (filter.industry) {
          const industryValue = Option.getOrNull(enterprise.industry)
          if (industryValue !== filter.industry) return false
        }
        if (filter.nameSearch) {
          const searchLower = filter.nameSearch.toLowerCase()
          if (!enterprise.name.toLowerCase().includes(searchLower)) return false
        }
        return true
      }

      return {
        create: (params: CreateEnterpriseParams) =>
          Effect.gen(function* () {
            const id = generateEnterpriseId()
            const now = yield* DateTime.now

            // Build hierarchy path - Enterprise is root level
            const hierarchyPath = HierarchyPath.root(id, params.name)

            const enterprise = new Enterprise({
              id,
              name: params.name,
              status: Option.getOrElse(params.status, () => 'active' as const),
              description: params.description,
              industry: params.industry,
              legalName: params.legalName,
              taxId: params.taxId,
              headquarters: params.headquarters,
              hierarchyPath,
              createdAt: now,
              updatedAt: Option.none(),
              location: Option.none(),
              metadata: Option.getOrElse(params.metadata, () => ({})),
              // Enterprise has no parent IDs (it's the root)
              enterpriseId: Option.none(),
              siteId: Option.none(),
              areaId: Option.none(),
              plantId: Option.none(),
              lineId: Option.none(),
              workCellId: Option.none(),
              machineId: Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, enterprise)
              return newMap
            })

            return enterprise
          }),

        get: (id: EnterpriseId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const enterprise = map.get(id)
              if (!enterprise) {
                return Effect.fail(new EnterpriseStateNotFoundError(id))
              }
              return Effect.succeed(enterprise)
            })
          ),

        set: (enterprise: Enterprise) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(enterprise.id, enterprise)
            return newMap
          }),

        list: (filter: EnterpriseFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let enterprises = Array.from(map.values()).filter((e) =>
                matchesFilter(e, filter)
              )

              // Sort by createdAt descending
              enterprises.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                enterprises = enterprises.slice(filter.offset)
              }
              if (filter.limit) {
                enterprises = enterprises.slice(0, filter.limit)
              }

              return enterprises
            })
          ),

        delete: (id: EnterpriseId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: EnterpriseId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: EnterpriseFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((e) => matchesFilter(e, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Factory
// =============================================================================

/**
 * Factory to create SQL-backed enterprise state from a repository.
 *
 * Bridges the state interface to the repository pattern.
 *
 * @param repo - Repository with SQL-backed operations
 * @returns EnterpriseStateShape implementation
 */
export const makeEnterpriseStateSql = (repo: {
  findById: (id: EnterpriseId) => Effect.Effect<Option.Option<Enterprise>, unknown>
  findAll: (filter: EnterpriseFilter) => Effect.Effect<readonly Enterprise[], unknown>
  insert: (enterprise: Enterprise) => Effect.Effect<Enterprise, unknown>
  update: (enterprise: Partial<Enterprise> & { id: EnterpriseId }) => Effect.Effect<Enterprise, unknown>
  delete: (id: EnterpriseId) => Effect.Effect<boolean, unknown>
  /** Insert with DB-generated ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateEnterpriseParams) => Effect.Effect<Enterprise, unknown>
}): EnterpriseStateShape => ({
  create: (params: CreateEnterpriseParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(Effect.orDie)
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = generateEnterpriseId()
          const now = yield* DateTime.now

          // Build hierarchy path - Enterprise is root level
          const hierarchyPath = HierarchyPath.root(id, params.name)

          const enterprise = new Enterprise({
            id,
            name: params.name,
            status: Option.getOrElse(params.status, () => 'active' as const),
            description: params.description,
            industry: params.industry,
            legalName: params.legalName,
            taxId: params.taxId,
            headquarters: params.headquarters,
            hierarchyPath,
            createdAt: now,
            updatedAt: Option.none(),
            location: Option.none(),
            metadata: Option.getOrElse(params.metadata, () => ({})),
            // Enterprise has no parent IDs (it's the root)
            enterpriseId: Option.none(),
            siteId: Option.none(),
            areaId: Option.none(),
            plantId: Option.none(),
            lineId: Option.none(),
            workCellId: Option.none(),
            machineId: Option.none(),
          })

          return yield* repo.insert(enterprise).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new EnterpriseStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new EnterpriseStateNotFoundError(id)))
    ),

  set: (enterprise) =>
    repo.findById(enterprise.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(enterprise as Partial<Enterprise> & { id: EnterpriseId })
          : repo.insert(enterprise)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((enterprises) => enterprises.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
