/**
 * LineState Service
 *
 * Effect.Service for production line state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * ISA-95 Hierarchy: Plant -> **Line** -> Machine -> Sensor
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { LineId, PlantId, EnterpriseId, SiteId, AreaId } from '../schemas/identifiers'
import { Line, CreateLineParams, makeLineId } from '../schemas/assets/line'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let lineCounter = 0

/** Generate a unique line ID for in-memory testing */
const generateLineId = (): LineId => makeLineId(`gen-${Date.now()}-${++lineCounter}`)

// =============================================================================
// Filter & Error Types
// =============================================================================

/** Filter for listing lines */
export interface LineFilter extends PaginationOptions {
  readonly plantId?: PlantId
  readonly status?: string
  readonly lineType?: string
}

/** Line state not found error */
export class LineStateNotFoundError {
  readonly _tag = 'LineStateNotFoundError'
  constructor(readonly lineId: LineId) {}
}

// =============================================================================
// Shape Interface
// =============================================================================

/**
 * Line State Service Shape
 *
 * Contract for line state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface LineStateShape {
  /** Create a new line (ID generated by implementation) */
  readonly create: (params: CreateLineParams) => Effect.Effect<Line>

  /** Get line by ID */
  readonly get: (id: LineId) => Effect.Effect<Line, LineStateNotFoundError>

  /** Set/update line state (upsert) - use for updates, not creates */
  readonly set: (line: Line) => Effect.Effect<void>

  /** List lines matching filter */
  readonly list: (filter: LineFilter) => Effect.Effect<readonly Line[]>

  /** Delete line by ID */
  readonly delete: (id: LineId) => Effect.Effect<boolean>

  /** Check if line exists */
  readonly exists: (id: LineId) => Effect.Effect<boolean>

  /** Count lines matching filter */
  readonly count: (filter: LineFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * LineState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* LineState
 *   const line = yield* state.get(lineId)
 * })
 * ```
 */
export class LineState extends Context.Tag('iiot/LineState')<
  LineState,
  LineStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory line state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const LineStateInMemory: Layer.Layer<LineState> = Layer.effect(
  LineState,
  Ref.make(new Map<LineId, Line>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (line: Line, filter: LineFilter): boolean => {
        if (filter.plantId) {
          const linePlantId = Option.getOrNull(line.plantId)
          if (linePlantId !== filter.plantId) return false
        }
        if (filter.status && line.status !== filter.status) return false
        if (filter.lineType) {
          const lineType = Option.getOrNull(line.lineType)
          if (lineType !== filter.lineType) return false
        }
        return true
      }

      return {
        create: (params: CreateLineParams) =>
          Effect.gen(function* () {
            const id = generateLineId()
            const now = yield* DateTime.now

            // Build hierarchy path - Line's parent is Plant
            const segments: PathSegment[] = [
              new PathSegment({ level: 'plant', id: params.plantId, name: Option.none() }),
              new PathSegment({ level: 'line', id, name: Option.some(params.name) }),
            ]

            const line = new Line({
              id,
              name: params.name,
              status: params.status ?? 'idle',
              hierarchyPath: HierarchyPath.fromSegments(segments),
              enterpriseId: Option.none(),
              siteId: Option.none(),
              areaId: Option.none(),
              plantId: Option.some(params.plantId),
              lineId: Option.none(),
              workCellId: Option.none(),
              machineId: Option.none(),
              createdAt: now,
              updatedAt: Option.none(),
              description: params.description !== undefined
                ? Option.some(params.description)
                : Option.none(),
              location: Option.none(),
              metadata: params.metadata ?? {},
              capacity: params.capacity !== undefined
                ? Option.some(params.capacity)
                : Option.none(),
              lineType: params.lineType !== undefined
                ? Option.some(params.lineType)
                : Option.none(),
              operatingHoursPerDay: params.operatingHoursPerDay !== undefined
                ? Option.some(params.operatingHoursPerDay)
                : Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, line)
              return newMap
            })
            return line
          }),

        get: (id: LineId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const line = map.get(id)
              if (!line) {
                return Effect.fail(new LineStateNotFoundError(id))
              }
              return Effect.succeed(line)
            })
          ),

        set: (line: Line) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(line.id, line)
            return newMap
          }),

        list: (filter: LineFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let lines = Array.from(map.values()).filter((l) =>
                matchesFilter(l, filter)
              )

              // Sort by createdAt descending
              lines.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                lines = lines.slice(filter.offset)
              }
              if (filter.limit) {
                lines = lines.slice(0, filter.limit)
              }

              return lines
            })
          ),

        delete: (id: LineId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: LineId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: LineFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((l) => matchesFilter(l, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Implementation
// =============================================================================

/**
 * SQL-backed line state implementation for production.
 *
 * Uses a repository for actual SQL operations.
 * This factory bridges the state interface to the repository pattern.
 *
 * @param repo - Repository with SQL-backed operations
 * @returns LineStateShape implementation
 */
export const makeLineStateSql = (repo: {
  findById: (id: LineId) => Effect.Effect<Option.Option<Line>, unknown>
  findAll: (filter: LineFilter) => Effect.Effect<readonly Line[], unknown>
  insert: (line: Line) => Effect.Effect<Line, unknown>
  update: (line: Partial<Line> & { id: LineId }) => Effect.Effect<Line, unknown>
  delete: (id: LineId) => Effect.Effect<boolean, unknown>
  /** Insert with DB-generated ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateLineParams) => Effect.Effect<Line, unknown>
}): LineStateShape => ({
  create: (params: CreateLineParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(
          Effect.orDie // SQL failures are defects
        )
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = generateLineId()
          const now = yield* DateTime.now

          const segments: PathSegment[] = [
            new PathSegment({ level: 'plant', id: params.plantId, name: Option.none() }),
            new PathSegment({ level: 'line', id, name: Option.some(params.name) }),
          ]

          const line = new Line({
            id,
            name: params.name,
            status: params.status ?? 'idle',
            hierarchyPath: HierarchyPath.fromSegments(segments),
            enterpriseId: Option.none(),
            siteId: Option.none(),
            areaId: Option.none(),
            plantId: Option.some(params.plantId),
            lineId: Option.none(),
            workCellId: Option.none(),
            machineId: Option.none(),
            createdAt: now,
            updatedAt: Option.none(),
            description: params.description !== undefined
              ? Option.some(params.description)
              : Option.none(),
            location: Option.none(),
            metadata: params.metadata ?? {},
            capacity: params.capacity !== undefined
              ? Option.some(params.capacity)
              : Option.none(),
            lineType: params.lineType !== undefined
              ? Option.some(params.lineType)
              : Option.none(),
            operatingHoursPerDay: params.operatingHoursPerDay !== undefined
              ? Option.some(params.operatingHoursPerDay)
              : Option.none(),
          })
          return yield* repo.insert(line).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new LineStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new LineStateNotFoundError(id)))
    ),

  set: (line) =>
    repo.findById(line.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(line as Partial<Line> & { id: LineId })
          : repo.insert(line)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((lines) => lines.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
