/**
 * SensorAssetState Service
 *
 * Effect.Service for sensor ASSET state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * NOTE: Named SensorAssetState to distinguish from SensorReading state.
 * This manages Sensor entities (metadata, thresholds, calibration),
 * NOT the time-series reading data.
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { MachineId, DeviceId } from '../schemas/identifiers'
import { Sensor, CreateSensorParams, makeSensorId, type SensorId, type SensorType } from '../schemas/assets/sensor'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let sensorCounter = 0

/** Generate a unique sensor ID for in-memory testing */
const generateSensorId = (): SensorId => makeSensorId(`gen-${Date.now()}-${++sensorCounter}`)

// =============================================================================
// Filter Type
// =============================================================================

/**
 * Filter for listing sensors.
 * Supports filtering by parent (machine or device), status, and sensor type.
 */
export interface SensorAssetFilter extends PaginationOptions {
  /** Filter by parent machine */
  readonly machineId?: MachineId
  /** Filter by parent device */
  readonly deviceId?: DeviceId
  /** Filter by asset status */
  readonly status?: string
  /** Filter by sensor type (temperature, pressure, etc.) */
  readonly sensorType?: SensorType
  /** Include only sensors needing calibration */
  readonly needsCalibration?: boolean
}

// =============================================================================
// Error Type
// =============================================================================

/**
 * Error when sensor asset is not found.
 */
export class SensorAssetStateNotFoundError {
  readonly _tag = 'SensorAssetStateNotFoundError'
  constructor(readonly sensorId: SensorId) {}
}

// =============================================================================
// Service Shape Interface
// =============================================================================

/**
 * SensorAssetState Service Shape
 *
 * Contract for sensor asset state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface SensorAssetStateShape {
  /** Create a new sensor asset (ID generated by implementation) */
  readonly create: (params: CreateSensorParams) => Effect.Effect<Sensor>

  /** Get sensor by ID */
  readonly get: (id: SensorId) => Effect.Effect<Sensor, SensorAssetStateNotFoundError>

  /** Set/update sensor state (upsert) - use for updates, not creates */
  readonly set: (sensor: Sensor) => Effect.Effect<void>

  /** List sensors matching filter */
  readonly list: (filter: SensorAssetFilter) => Effect.Effect<readonly Sensor[]>

  /** Delete sensor by ID */
  readonly delete: (id: SensorId) => Effect.Effect<boolean>

  /** Check if sensor exists */
  readonly exists: (id: SensorId) => Effect.Effect<boolean>

  /** Count sensors matching filter */
  readonly count: (filter: SensorAssetFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * SensorAssetState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* SensorAssetState
 *   const sensor = yield* state.get(sensorId)
 * })
 * ```
 */
export class SensorAssetState extends Context.Tag('iiot/SensorAssetState')<
  SensorAssetState,
  SensorAssetStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory sensor asset state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const SensorAssetStateInMemory: Layer.Layer<SensorAssetState> = Layer.effect(
  SensorAssetState,
  Ref.make(new Map<SensorId, Sensor>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (sensor: Sensor, filter: SensorAssetFilter): boolean => {
        // Filter by machineId (from BaseAssetFields)
        if (filter.machineId) {
          if (Option.isNone(sensor.machineId) || sensor.machineId.value !== filter.machineId) {
            return false
          }
        }

        // Filter by deviceId - check hierarchyPath for device parent
        if (filter.deviceId) {
          // Sensors may have device as parent in hierarchy
          const hasDevice = sensor.hierarchyPath.segments.some(
            (seg) => seg.level === 'device' && seg.id === filter.deviceId
          )
          if (!hasDevice) return false
        }

        // Filter by status
        if (filter.status && sensor.status !== filter.status) return false

        // Filter by sensor type
        if (filter.sensorType && sensor.sensorType !== filter.sensorType) return false

        // Filter by calibration needed
        if (filter.needsCalibration) {
          const now = new Date()
          if (!sensor.isCalibrationOverdue(now)) return false
        }

        return true
      }

      return {
        create: (params: CreateSensorParams) =>
          Effect.gen(function* () {
            const id = makeSensorId(params.slug)
            const now = yield* DateTime.now

            // Build hierarchy path from machineId
            // In real impl, would look up machine's path and append
            const segments: PathSegment[] = [
              new PathSegment({
                level: 'machine',
                id: params.machineId,
                name: 'Machine', // Would be looked up
              }),
              new PathSegment({
                level: 'sensor',
                id,
                name: params.name,
              }),
            ]

            const sensor = new Sensor({
              id,
              name: params.name,
              status: params.status ?? 'active',
              hierarchyPath: HierarchyPath.fromSegments(segments),
              machineId: Option.some(params.machineId),
              sensorType: params.sensorType,
              unit: params.unit,
              sampleRateMs: params.sampleRateMs !== undefined ? Option.some(params.sampleRateMs) : Option.none(),
              thresholdHigh: params.thresholdHigh !== undefined ? Option.some(params.thresholdHigh) : Option.none(),
              thresholdCritical: params.thresholdCritical !== undefined ? Option.some(params.thresholdCritical) : Option.none(),
              thresholdLow: params.thresholdLow !== undefined ? Option.some(params.thresholdLow) : Option.none(),
              thresholdCriticalLow: params.thresholdCriticalLow !== undefined ? Option.some(params.thresholdCriticalLow) : Option.none(),
              lastCalibrationDate: Option.none(),
              nextCalibrationDate: Option.none(),
              opcUaNodeId: params.opcUaNodeId !== undefined ? Option.some(params.opcUaNodeId) : Option.none(),
              description: params.description !== undefined ? Option.some(params.description) : Option.none(),
              location: Option.none(),
              metadata: params.metadata ?? {},
              createdAt: now,
              updatedAt: Option.none(),
              // BaseAssetFields parent references
              enterpriseId: Option.none(),
              siteId: Option.none(),
              areaId: Option.none(),
              plantId: Option.none(),
              lineId: Option.none(),
              workCellId: Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, sensor)
              return newMap
            })

            return sensor
          }),

        get: (id: SensorId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const sensor = map.get(id)
              if (!sensor) {
                return Effect.fail(new SensorAssetStateNotFoundError(id))
              }
              return Effect.succeed(sensor)
            })
          ),

        set: (sensor: Sensor) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(sensor.id, sensor)
            return newMap
          }),

        list: (filter: SensorAssetFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let sensors = Array.from(map.values()).filter((s) =>
                matchesFilter(s, filter)
              )

              // Sort by createdAt descending
              sensors.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                sensors = sensors.slice(filter.offset)
              }
              if (filter.limit) {
                sensors = sensors.slice(0, filter.limit)
              }

              return sensors
            })
          ),

        delete: (id: SensorId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: SensorId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: SensorAssetFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((s) => matchesFilter(s, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Implementation
// =============================================================================

/**
 * SQL-backed sensor asset state implementation for production.
 *
 * Uses the existing SensorRepo for actual SQL operations.
 * This layer bridges the state interface to the repository pattern.
 *
 * For the full SQL implementation, see SensorRepo.
 */
export const makeSensorAssetStateSql = (repo: {
  findById: (id: SensorId) => Effect.Effect<Option.Option<Sensor>, unknown>
  findAll: (filter: SensorAssetFilter) => Effect.Effect<readonly Sensor[], unknown>
  insert: (sensor: Sensor) => Effect.Effect<Sensor, unknown>
  update: (sensor: Partial<Sensor> & { id: SensorId }) => Effect.Effect<Sensor, unknown>
  delete: (id: SensorId) => Effect.Effect<boolean, unknown>
  /** Insert with params and generate ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateSensorParams) => Effect.Effect<Sensor, unknown>
}): SensorAssetStateShape => ({
  create: (params: CreateSensorParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(
          Effect.orDie // SQL failures are defects
        )
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = makeSensorId(params.slug)
          const now = yield* DateTime.now

          // Build hierarchy path from machineId
          const segments: PathSegment[] = [
            new PathSegment({
              level: 'machine',
              id: params.machineId,
              name: 'Machine',
            }),
            new PathSegment({
              level: 'sensor',
              id,
              name: params.name,
            }),
          ]

          const sensor = new Sensor({
            id,
            name: params.name,
            status: params.status ?? 'active',
            hierarchyPath: HierarchyPath.fromSegments(segments),
            machineId: Option.some(params.machineId),
            sensorType: params.sensorType,
            unit: params.unit,
            sampleRateMs: params.sampleRateMs !== undefined ? Option.some(params.sampleRateMs) : Option.none(),
            thresholdHigh: params.thresholdHigh !== undefined ? Option.some(params.thresholdHigh) : Option.none(),
            thresholdCritical: params.thresholdCritical !== undefined ? Option.some(params.thresholdCritical) : Option.none(),
            thresholdLow: params.thresholdLow !== undefined ? Option.some(params.thresholdLow) : Option.none(),
            thresholdCriticalLow: params.thresholdCriticalLow !== undefined ? Option.some(params.thresholdCriticalLow) : Option.none(),
            lastCalibrationDate: Option.none(),
            nextCalibrationDate: Option.none(),
            opcUaNodeId: params.opcUaNodeId !== undefined ? Option.some(params.opcUaNodeId) : Option.none(),
            description: params.description !== undefined ? Option.some(params.description) : Option.none(),
            location: Option.none(),
            metadata: params.metadata ?? {},
            createdAt: now,
            updatedAt: Option.none(),
            enterpriseId: Option.none(),
            siteId: Option.none(),
            areaId: Option.none(),
            plantId: Option.none(),
            lineId: Option.none(),
            workCellId: Option.none(),
          })

          return yield* repo.insert(sensor).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new SensorAssetStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new SensorAssetStateNotFoundError(id)))
    ),

  set: (sensor) =>
    repo.findById(sensor.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(sensor as Partial<Sensor> & { id: SensorId })
          : repo.insert(sensor)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((sensors) => sensors.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
