/**
 * SiteState Service
 *
 * Effect.Service for site state management with swappable implementations.
 * Provides in-memory (testing) and SQL (production) layers.
 *
 * @module
 */

import { Effect, Context, Layer, Option, Ref, DateTime } from 'effect'
import type { SiteId, EnterpriseId } from '../schemas/identifiers'
import { Site, CreateSiteParams, makeSiteId } from '../schemas/assets/site'
import { HierarchyPath, PathSegment } from '../schemas/hierarchy'
import type { PaginationOptions } from './StateShape'

// =============================================================================
// ID Generation
// =============================================================================

let siteCounter = 0

/** Generate a unique site ID for in-memory testing */
const generateSiteId = (): SiteId => makeSiteId(`gen-${Date.now()}-${++siteCounter}`)

// =============================================================================
// Filter Types
// =============================================================================

/** Filter for listing sites */
export interface SiteFilter extends PaginationOptions {
  readonly enterpriseId?: EnterpriseId
  readonly status?: string
}

// =============================================================================
// Error Types
// =============================================================================

/** Site state not found error */
export class SiteStateNotFoundError {
  readonly _tag = 'SiteStateNotFoundError'
  constructor(readonly siteId: SiteId) {}
}

// =============================================================================
// Service Shape
// =============================================================================

/**
 * Site State Service Shape
 *
 * Contract for site state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface SiteStateShape {
  /** Create a new site (ID generated by implementation) */
  readonly create: (params: CreateSiteParams) => Effect.Effect<Site>

  /** Get site by ID */
  readonly get: (id: SiteId) => Effect.Effect<Site, SiteStateNotFoundError>

  /** Set/update site state (upsert) - use for updates, not creates */
  readonly set: (site: Site) => Effect.Effect<void>

  /** List sites matching filter */
  readonly list: (filter: SiteFilter) => Effect.Effect<readonly Site[]>

  /** Delete site by ID */
  readonly delete: (id: SiteId) => Effect.Effect<boolean>

  /** Check if site exists */
  readonly exists: (id: SiteId) => Effect.Effect<boolean>

  /** Count sites matching filter */
  readonly count: (filter: SiteFilter) => Effect.Effect<number>
}

// =============================================================================
// Service Definition
// =============================================================================

/**
 * SiteState Service Tag
 *
 * Usage:
 * ```ts
 * const program = Effect.gen(function* () {
 *   const state = yield* SiteState
 *   const site = yield* state.get(siteId)
 * })
 * ```
 */
export class SiteState extends Context.Tag('iiot/SiteState')<
  SiteState,
  SiteStateShape
>() {}

// =============================================================================
// In-Memory Implementation
// =============================================================================

/**
 * In-memory site state implementation for testing.
 *
 * Uses a Map for O(1) lookup. Not suitable for production due to:
 * - No persistence
 * - No cross-process sharing
 * - Memory limits
 */
export const SiteStateInMemory: Layer.Layer<SiteState> = Layer.effect(
  SiteState,
  Ref.make(new Map<SiteId, Site>()).pipe(
    Effect.map((store) => {
      const matchesFilter = (site: Site, filter: SiteFilter): boolean => {
        if (filter.enterpriseId && site.enterpriseId !== filter.enterpriseId) return false
        if (filter.status && site.status !== filter.status) return false
        return true
      }

      return {
        create: (params: CreateSiteParams) =>
          Effect.gen(function* () {
            const id = generateSiteId()
            const now = yield* DateTime.now

            // Build hierarchy path: Enterprise -> Site
            const enterpriseSegment = new PathSegment({
              level: 'enterprise',
              id: params.enterpriseId,
              name: Option.none(),
            })
            const siteSegment = new PathSegment({
              level: 'site',
              id: id,
              name: Option.some(params.name),
            })
            const hierarchyPath = HierarchyPath.fromSegments([enterpriseSegment, siteSegment])

            const site = new Site({
              id,
              name: params.name,
              enterpriseId: params.enterpriseId,
              timezone: params.timezone,
              status: Option.getOrElse(params.status, () => 'planned' as const),
              description: params.description !== undefined ? Option.some(params.description) : Option.none(),
              location: params.location,
              metadata: Option.getOrElse(params.metadata, () => ({})),
              address: params.address !== undefined ? Option.some(params.address) : Option.none(),
              city: params.city !== undefined ? Option.some(params.city) : Option.none(),
              state: params.state !== undefined ? Option.some(params.state) : Option.none(),
              country: params.country !== undefined ? Option.some(params.country) : Option.none(),
              postalCode: params.postalCode !== undefined ? Option.some(params.postalCode) : Option.none(),
              hierarchyPath,
              createdAt: now,
              updatedAt: Option.none(),
              // Parent IDs - Site only has enterpriseId as required parent
              siteId: Option.none(),
              areaId: Option.none(),
              plantId: Option.none(),
              lineId: Option.none(),
              workCellId: Option.none(),
              machineId: Option.none(),
            })

            yield* Ref.update(store, (map) => {
              const newMap = new Map(map)
              newMap.set(id, site)
              return newMap
            })

            return site
          }),

        get: (id: SiteId) =>
          Ref.get(store).pipe(
            Effect.flatMap((map) => {
              const site = map.get(id)
              if (!site) {
                return Effect.fail(new SiteStateNotFoundError(id))
              }
              return Effect.succeed(site)
            })
          ),

        set: (site: Site) =>
          Ref.update(store, (map) => {
            const newMap = new Map(map)
            newMap.set(site.id, site)
            return newMap
          }),

        list: (filter: SiteFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) => {
              let sites = Array.from(map.values()).filter((s) =>
                matchesFilter(s, filter)
              )

              // Sort by createdAt descending
              sites.sort((a, b) =>
                Number(b.createdAt.epochMillis) - Number(a.createdAt.epochMillis)
              )

              // Apply pagination
              if (filter.offset) {
                sites = sites.slice(filter.offset)
              }
              if (filter.limit) {
                sites = sites.slice(0, filter.limit)
              }

              return sites
            })
          ),

        delete: (id: SiteId) =>
          Ref.modify(store, (map) => {
            const existed = map.has(id)
            if (existed) {
              const newMap = new Map(map)
              newMap.delete(id)
              return [true, newMap] as const
            }
            return [false, map] as const
          }),

        exists: (id: SiteId) =>
          Ref.get(store).pipe(Effect.map((map) => map.has(id))),

        count: (filter: SiteFilter) =>
          Ref.get(store).pipe(
            Effect.map((map) =>
              Array.from(map.values()).filter((s) => matchesFilter(s, filter)).length
            )
          ),
      }
    })
  )
)

// =============================================================================
// SQL Implementation
// =============================================================================

/**
 * SQL-backed site state implementation for production.
 *
 * Uses a repository pattern for actual SQL operations.
 * This factory bridges the state interface to the repository pattern.
 */
export const makeSiteStateSql = (repo: {
  findById: (id: SiteId) => Effect.Effect<Option.Option<Site>, unknown>
  findAll: (filter: SiteFilter) => Effect.Effect<readonly Site[], unknown>
  insert: (site: Site) => Effect.Effect<Site, unknown>
  update: (site: Partial<Site> & { id: SiteId }) => Effect.Effect<Site, unknown>
  delete: (id: SiteId) => Effect.Effect<boolean, unknown>
  /** Insert with DB-generated ID. If not provided, falls back to insert() */
  insertWithGeneratedId?: (params: CreateSiteParams) => Effect.Effect<Site, unknown>
}): SiteStateShape => ({
  create: (params: CreateSiteParams) =>
    repo.insertWithGeneratedId
      ? repo.insertWithGeneratedId(params).pipe(
          Effect.orDie // SQL failures are defects
        )
      : Effect.gen(function* () {
          // Fallback: generate ID client-side if repo doesn't support generated IDs
          const id = generateSiteId()
          const now = yield* DateTime.now

          // Build hierarchy path
          const enterpriseSegment = new PathSegment({
            level: 'enterprise',
            id: params.enterpriseId,
            name: Option.none(),
          })
          const siteSegment = new PathSegment({
            level: 'site',
            id: id,
            name: Option.some(params.name),
          })
          const hierarchyPath = HierarchyPath.fromSegments([enterpriseSegment, siteSegment])

          const site = new Site({
            id,
            name: params.name,
            enterpriseId: params.enterpriseId,
            timezone: params.timezone,
            status: Option.getOrElse(params.status, () => 'planned' as const),
            description: params.description !== undefined ? Option.some(params.description) : Option.none(),
            location: params.location,
            metadata: Option.getOrElse(params.metadata, () => ({})),
            address: params.address !== undefined ? Option.some(params.address) : Option.none(),
            city: params.city !== undefined ? Option.some(params.city) : Option.none(),
            state: params.state !== undefined ? Option.some(params.state) : Option.none(),
            country: params.country !== undefined ? Option.some(params.country) : Option.none(),
            postalCode: params.postalCode !== undefined ? Option.some(params.postalCode) : Option.none(),
            hierarchyPath,
            createdAt: now,
            updatedAt: Option.none(),
            siteId: Option.none(),
            areaId: Option.none(),
            plantId: Option.none(),
            lineId: Option.none(),
            workCellId: Option.none(),
            machineId: Option.none(),
          })
          return yield* repo.insert(site).pipe(Effect.orDie)
        }),

  get: (id) =>
    repo.findById(id).pipe(
      Effect.flatMap((opt) =>
        Option.isSome(opt)
          ? Effect.succeed(opt.value)
          : Effect.fail(new SiteStateNotFoundError(id))
      ),
      Effect.catchAll(() => Effect.fail(new SiteStateNotFoundError(id)))
    ),

  set: (site) =>
    repo.findById(site.id).pipe(
      Effect.flatMap((existing) =>
        Option.isSome(existing)
          ? repo.update(site as Partial<Site> & { id: SiteId })
          : repo.insert(site)
      ),
      Effect.asVoid,
      Effect.catchAll(() => Effect.void)
    ),

  list: (filter) =>
    repo.findAll(filter).pipe(
      Effect.catchAll(() => Effect.succeed([]))
    ),

  delete: (id) =>
    repo.delete(id).pipe(
      Effect.catchAll(() => Effect.succeed(false))
    ),

  exists: (id) =>
    repo.findById(id).pipe(
      Effect.map(Option.isSome),
      Effect.catchAll(() => Effect.succeed(false))
    ),

  count: (filter) =>
    repo.findAll({ ...filter, limit: undefined, offset: undefined }).pipe(
      Effect.map((sites) => sites.length),
      Effect.catchAll(() => Effect.succeed(0))
    ),
})
