/**
 * State Service Shape Interfaces
 *
 * Defines the contracts for state services that can be swapped between
 * in-memory (testing) and SQL (production) implementations.
 *
 * Design Principles:
 * - All methods return Effect for consistent async handling
 * - Read methods return Option for nullable results
 * - Write methods are idempotent where possible
 * - Filter types are defined per-domain for type safety
 *
 * @module
 */

import { Effect, Option } from 'effect'
import type {
  AlarmId,
  WorkOrderId,
  MachineId,
  LineId,
  WorkCellId,
} from '../schemas/identifiers'
import type { Alarm, AlarmState as AlarmStateType, CreateAlarmParams } from '../schemas/alarms'
import type { WorkOrder, WorkOrderStatus } from '../schemas/work-orders'
import type {
  EquipmentStateId,
  EquipmentState,
  StateType,
  StateReason,
} from '../schemas/equipment-state/schema'
import type { WorkCell, CreateWorkCellParams } from '../schemas/assets/workcell'

// =============================================================================
// Create Input Types (without ID - for DB-generated IDs)
// =============================================================================

/** Input for creating a new work order (ID generated by DB) */
export interface CreateWorkOrderInput {
  readonly workflowDefinitionId: string
  readonly workflowVersion: string
  readonly type: string
  readonly priority: string
  readonly title: string
  readonly description: string
  readonly createdBy: string
  readonly scheduledStart: Option.Option<Date>
  readonly dueDate: Option.Option<Date>
  readonly parentWorkOrderId: Option.Option<string>
  readonly primaryAssetId: Option.Option<string>
  readonly assignedTo: Option.Option<string>
  readonly metadata?: Record<string, unknown>
}

/** Input for creating a new equipment state (ID generated by DB) */
export interface CreateEquipmentStateInput {
  readonly machineId: MachineId
  readonly state: StateType
  readonly reason: Option.Option<StateReason>
  readonly operatorId: Option.Option<string>
  readonly notes: Option.Option<string>
}

// =============================================================================
// Common Types
// =============================================================================

/** Pagination options */
export interface PaginationOptions {
  readonly limit?: number
  readonly offset?: number
}

/** Time range filter */
export interface TimeRangeFilter {
  readonly since?: Date
  readonly until?: Date
}

// =============================================================================
// Alarm State Shape
// =============================================================================

/** Filter for listing alarms */
export interface AlarmFilter extends PaginationOptions, TimeRangeFilter {
  readonly deviceId?: string
  readonly assetId?: string
  readonly severity?: string
  readonly state?: AlarmStateType
  readonly onlyActive?: boolean
  readonly onlyRequiresAttention?: boolean
}

/** Alarm state not found error */
export class AlarmStateNotFoundError {
  readonly _tag = 'AlarmStateNotFoundError'
  constructor(readonly alarmId: AlarmId) {}
}

/**
 * Alarm State Service Shape
 *
 * Contract for alarm state storage. Implementations must provide
 * consistent behavior for get/set/list/delete operations.
 */
export interface AlarmStateShape {
  /** Create a new alarm (ID generated by implementation) */
  readonly create: (params: CreateAlarmParams) => Effect.Effect<Alarm>

  /** Get alarm by ID */
  readonly get: (id: AlarmId) => Effect.Effect<Alarm, AlarmStateNotFoundError>

  /** Set/update alarm state (upsert) - use for updates, not creates */
  readonly set: (alarm: Alarm) => Effect.Effect<void>

  /** List alarms matching filter */
  readonly list: (filter: AlarmFilter) => Effect.Effect<readonly Alarm[]>

  /** Delete alarm by ID */
  readonly delete: (id: AlarmId) => Effect.Effect<boolean>

  /** Check if alarm exists */
  readonly exists: (id: AlarmId) => Effect.Effect<boolean>

  /** Count alarms matching filter */
  readonly count: (filter: AlarmFilter) => Effect.Effect<number>
}

// =============================================================================
// WorkOrder State Shape
// =============================================================================

/** Filter for listing work orders */
export interface WorkOrderFilter extends PaginationOptions, TimeRangeFilter {
  readonly status?: readonly WorkOrderStatus[]
  readonly type?: readonly string[]
  readonly priority?: readonly string[]
  readonly assignedTo?: string
  readonly primaryAssetId?: string
  readonly includeOverdue?: boolean
}

/** Work order state not found error */
export class WorkOrderStateNotFoundError {
  readonly _tag = 'WorkOrderStateNotFoundError'
  constructor(readonly workOrderId: WorkOrderId) {}
}

/**
 * WorkOrder State Service Shape
 *
 * Contract for work order state storage. Tracks full lifecycle
 * from creation through completion/closure.
 */
export interface WorkOrderStateShape {
  /** Create a new work order (ID generated by implementation) */
  readonly create: (input: CreateWorkOrderInput) => Effect.Effect<WorkOrder>

  /** Get work order by ID */
  readonly get: (id: WorkOrderId) => Effect.Effect<WorkOrder, WorkOrderStateNotFoundError>

  /** Set/update work order state (upsert) - use for updates, not creates */
  readonly set: (workOrder: WorkOrder) => Effect.Effect<void>

  /** List work orders matching filter */
  readonly list: (filter: WorkOrderFilter) => Effect.Effect<readonly WorkOrder[]>

  /** Delete work order by ID */
  readonly delete: (id: WorkOrderId) => Effect.Effect<boolean>

  /** Check if work order exists */
  readonly exists: (id: WorkOrderId) => Effect.Effect<boolean>

  /** Count work orders matching filter */
  readonly count: (filter: WorkOrderFilter) => Effect.Effect<number>
}

// =============================================================================
// EquipmentState Shape
// =============================================================================

/** Filter for listing equipment states */
export interface EquipmentStateFilter extends PaginationOptions, TimeRangeFilter {
  readonly machineId?: MachineId
  readonly state?: StateType
  readonly reason?: string
  readonly onlyActive?: boolean
}

/** Equipment state not found error */
export class EquipmentStateNotFoundError {
  readonly _tag = 'EquipmentStateNotFoundError'
  constructor(readonly stateId: EquipmentStateId) {}
}

/** Machine state not found error */
export class MachineStateNotFoundError {
  readonly _tag = 'MachineStateNotFoundError'
  constructor(readonly machineId: MachineId) {}
}

/**
 * EquipmentState Service Shape
 *
 * Contract for equipment state storage. Tracks machine state transitions
 * for OEE calculations and downtime analysis.
 */
export interface EquipmentStateShapeInterface {
  /** Create a new equipment state (ID generated by implementation) */
  readonly create: (input: CreateEquipmentStateInput) => Effect.Effect<EquipmentState>

  /** Get equipment state by ID */
  readonly get: (id: EquipmentStateId) => Effect.Effect<EquipmentState, EquipmentStateNotFoundError>

  /** Get current (active) state for a machine */
  readonly getCurrent: (machineId: MachineId) => Effect.Effect<Option.Option<EquipmentState>>

  /** Set/update equipment state (upsert) - use for updates, not creates */
  readonly set: (state: EquipmentState) => Effect.Effect<void>

  /** List equipment states matching filter */
  readonly list: (filter: EquipmentStateFilter) => Effect.Effect<readonly EquipmentState[]>

  /** End current state for a machine (set endedAt) */
  readonly endCurrent: (machineId: MachineId, endedAt: Date) => Effect.Effect<boolean>

  /** Delete equipment state by ID */
  readonly delete: (id: EquipmentStateId) => Effect.Effect<boolean>

  /** Count states matching filter */
  readonly count: (filter: EquipmentStateFilter) => Effect.Effect<number>
}

// =============================================================================
// WorkCell State Shape
// =============================================================================

/** Filter for listing work cells */
export interface WorkCellFilter extends PaginationOptions, TimeRangeFilter {
  /** Filter by parent line ID */
  readonly lineId?: LineId
  /** Filter by operational status */
  readonly status?: string
  /** Filter by cell type */
  readonly cellType?: string
  /** Filter only operational work cells (not maintenance/decommissioned) */
  readonly onlyOperational?: boolean
}

/** Work cell state not found error */
export class WorkCellStateNotFoundError {
  readonly _tag = 'WorkCellStateNotFoundError'
  constructor(readonly workCellId: WorkCellId) {}
}

/**
 * WorkCell State Service Shape
 *
 * Contract for work cell state storage. WorkCells are ISA-95 Level 1 entities
 * (Work Units) that sit between Lines and Machines in the hierarchy.
 */
export interface WorkCellStateShape {
  /** Create a new work cell (ID generated by implementation) */
  readonly create: (params: CreateWorkCellParams) => Effect.Effect<WorkCell>

  /** Get work cell by ID */
  readonly get: (id: WorkCellId) => Effect.Effect<WorkCell, WorkCellStateNotFoundError>

  /** Set/update work cell state (upsert) - use for updates, not creates */
  readonly set: (workCell: WorkCell) => Effect.Effect<void>

  /** List work cells matching filter */
  readonly list: (filter: WorkCellFilter) => Effect.Effect<readonly WorkCell[]>

  /** Delete work cell by ID */
  readonly delete: (id: WorkCellId) => Effect.Effect<boolean>

  /** Check if work cell exists */
  readonly exists: (id: WorkCellId) => Effect.Effect<boolean>

  /** Count work cells matching filter */
  readonly count: (filter: WorkCellFilter) => Effect.Effect<number>
}
