/**
 * Durable Stream kernel for the MSH-backed bridge.
 *
 * This module is deliberately pure LNK domain logic. It knows nothing about
 * NATS clients, JetStream handles, KV buckets, or MSH implementation details.
 * The live bridge feeds it revisioned metadata loaded from the typed MSH KV
 * service, publishes the returned `DurableBatchEnvelope`, then commits the
 * returned metadata via KV CAS. Substrate downstairs, protocol law up here.
 *
 * @module @tmnl/lnk/services/wire/nats-bridge/kernel
 */

import * as Effect from "effect/Effect"
import * as Schema from "effect/Schema"

import { ContentType } from "../../../contracts/ContentType.js"
import { Offset, trust as trustOffset, type ReadPosition } from "../../../contracts/Offset.js"
import { Epoch, ProducerId, Seq, type ProducerId as ProducerIdT } from "../../../contracts/Producer.js"
import { StreamId } from "../../../contracts/StreamId.js"
import {
  InvalidPayloadError,
  SequenceGapError,
  StaleEpochError,
  StreamClosedError,
  StreamConfigMismatchError,
} from "../../../contracts/errors.js"

// ─── Schema-backed metadata persisted in MSH KV ─────────────────────────────

export const DurableProducerState = Schema.Struct({
  epoch: Epoch,
  lastSeq: Seq,
  /** Offset of the last logical message accepted for this producer. */
  lastBatchEndOffset: Offset,
})
export type DurableProducerState = typeof DurableProducerState.Type

export const DurableStreamMetadata = Schema.Struct({
  version: Schema.Literal(1),
  streamId: StreamId,
  contentType: ContentType,
  closed: Schema.Boolean,
  createdAtMillis: Schema.Number,
  /** Optional Stream-TTL value in seconds. */
  ttl: Schema.optional(Schema.Number),
  /** Optional Stream-Expires-At ISO-8601 timestamp. */
  expiresAt: Schema.optional(Schema.String),
  /** Optional schema identifier attached by PUT. */
  schemaId: Schema.optional(Schema.String),
  /** Offset of the last logical message appended. Absent for empty streams. */
  lastOffset: Schema.optional(Offset),
  /** Next logical message sequence to allocate. */
  nextSeq: Schema.Number,
  /** Cumulative byte offset for the next logical message. */
  nextByteOffset: Schema.Number,
  /** Last JetStream subject sequence committed into metadata. `0` means empty. */
  lastSubjectSequence: Schema.Number,
  /** Last accepted Stream-Seq header value, if any. */
  lastStreamSeq: Schema.optional(Schema.String),
  /** Highest accepted producer state, keyed by Producer-Id. */
  producers: Schema.Record(Schema.String, DurableProducerState),
})
export type DurableStreamMetadata = typeof DurableStreamMetadata.Type

// ─── Batch envelope persisted as one JetStream message ──────────────────────

export const DurableBatchMessage = Schema.Struct({
  offset: Offset,
  byteLength: Schema.Number,
  body: Schema.Uint8ArrayFromBase64,
})
export type DurableBatchMessage = typeof DurableBatchMessage.Type

export const DurableBatchEnvelope = Schema.Struct({
  version: Schema.Literal(1),
  streamId: StreamId,
  contentType: ContentType,
  baseSeq: Schema.Number,
  baseByteOffset: Schema.Number,
  messages: Schema.Array(DurableBatchMessage),
  producerId: Schema.optional(ProducerId),
  producerEpoch: Schema.optional(Epoch),
  producerSeq: Schema.optional(Seq),
  streamSeq: Schema.optional(Schema.String),
  streamClosed: Schema.Boolean,
})
export type DurableBatchEnvelope = typeof DurableBatchEnvelope.Type

// ─── Offset codec ───────────────────────────────────────────────────────────

const PAD = 20
const OFFSET_PREFIX = "msh"
const OFFSET_RE = /^msh:(\d{20})_(\d{20})$/

const padNum = (n: number): string => String(n).padStart(PAD, "0")

/** Internal server-side offset constructor. Clients still treat this as opaque. */
export const makeMshOffset = (seq: number, byteOffset: number): Offset =>
  trustOffset(`${OFFSET_PREFIX}:${padNum(seq)}_${padNum(byteOffset)}`)

export interface DecodedMshOffset {
  readonly seq: number
  readonly byteOffset: number
}

/** Server-side parser for offsets generated by this bridge. Returns null for foreign offsets. */
export const decodeMshOffset = (offset: Offset): DecodedMshOffset | null => {
  const match = OFFSET_RE.exec(offset as string)
  if (!match) return null
  return {
    seq: Number(match[1]),
    byteOffset: Number(match[2]),
  }
}

export const positionToStartSeq = (
  position: ReadPosition,
  metadata: DurableStreamMetadata,
): number | "now" | null => {
  if (position === "-1") return 0
  if (position === "now") return "now"
  const decoded = decodeMshOffset(position)
  return decoded ? decoded.seq + 1 : null
}

// ─── Create planning ────────────────────────────────────────────────────────

export interface DurableCreateInput {
  readonly streamId: typeof StreamId.Type
  readonly contentType: typeof ContentType.Type
  readonly streamClosed?: boolean
  readonly ttl?: number
  readonly expiresAt?: string
  readonly schemaId?: string
  readonly nowMillis?: number
}

export interface DurableCreatePlan {
  readonly metadata: DurableStreamMetadata
  readonly created: boolean
  /** True when the caller must CAS-write metadata. */
  readonly needsCommit: boolean
}

const sameContentType = (a: typeof ContentType.Type, b: typeof ContentType.Type): boolean =>
  (a as string).toLowerCase() === (b as string).toLowerCase()

const producerKey = (producerId: ProducerIdT): string => producerId as string

const withProducerState = (
  metadata: DurableStreamMetadata,
  producer: DurableAppendInput["producer"],
  lastBatchEndOffset: Offset,
): DurableStreamMetadata["producers"] => {
  if (!producer) return metadata.producers
  return {
    ...metadata.producers,
    [producerKey(producer.producerId)]: {
      epoch: producer.epoch,
      lastSeq: producer.seq,
      lastBatchEndOffset,
    },
  }
}

export const makeInitialMetadata = (input: DurableCreateInput): DurableStreamMetadata => ({
  version: 1,
  streamId: input.streamId,
  contentType: input.contentType,
  closed: input.streamClosed === true,
  createdAtMillis: input.nowMillis ?? Date.now(),
  ...(input.ttl !== undefined ? { ttl: input.ttl } : {}),
  ...(input.expiresAt !== undefined ? { expiresAt: input.expiresAt } : {}),
  ...(input.schemaId !== undefined ? { schemaId: input.schemaId } : {}),
  nextSeq: 0,
  nextByteOffset: 0,
  lastSubjectSequence: 0,
  producers: {},
})

export const planCreate = (
  existing: DurableStreamMetadata | null,
  input: DurableCreateInput,
): Effect.Effect<DurableCreatePlan, StreamConfigMismatchError> =>
  Effect.gen(function* () {
    if (!existing) {
      return {
        metadata: makeInitialMetadata(input),
        created: true,
        needsCommit: true,
      }
    }

    if (!sameContentType(existing.contentType, input.contentType)) {
      return yield* new StreamConfigMismatchError({
        streamId: input.streamId,
        expectedContentType: existing.contentType as string,
        receivedContentType: input.contentType as string,
      })
    }

    const ttl = input.ttl
    const expiresAt = input.expiresAt
    if (
      (ttl !== undefined && existing.ttl !== ttl) ||
      (expiresAt !== undefined && existing.expiresAt !== expiresAt)
    ) {
      return yield* new StreamConfigMismatchError({
        streamId: input.streamId,
        expectedContentType: existing.contentType as string,
        receivedContentType: input.contentType as string,
      })
    }

    if (input.streamClosed === true && !existing.closed) {
      return {
        metadata: { ...existing, closed: true },
        created: false,
        needsCommit: true,
      }
    }

    return {
      metadata: existing,
      created: false,
      needsCommit: false,
    }
  })

// ─── Append planning ────────────────────────────────────────────────────────

export interface DurableAppendInput {
  readonly streamId: typeof StreamId.Type
  readonly contentType?: typeof ContentType.Type
  readonly messages: ReadonlyArray<Uint8Array>
  readonly producer?: {
    readonly producerId: ProducerIdT
    readonly epoch: typeof Epoch.Type
    readonly seq: typeof Seq.Type
  }
  readonly streamSeq?: string
  readonly streamClosed?: boolean
}

export interface DurableAppendResult {
  readonly nextOffset: Offset
  readonly duplicate: boolean
  readonly closed: boolean
  readonly producerEpoch?: typeof Epoch.Type
  readonly producerSeq?: typeof Seq.Type
}

export interface PublishAckInput {
  readonly subjectSequence: number
}

export interface DurableAppendDuplicatePlan {
  readonly _tag: "Duplicate"
  readonly result: DurableAppendResult
  readonly metadata: DurableStreamMetadata
}

export interface DurableAppendMetadataOnlyPlan {
  readonly _tag: "MetadataOnly"
  readonly result: DurableAppendResult
  readonly metadata: DurableStreamMetadata
}

export interface DurableAppendPublishPlan {
  readonly _tag: "Publish"
  readonly result: DurableAppendResult
  readonly envelope: DurableBatchEnvelope
  readonly msgID: string
  readonly expectedLastSubjectSequence: number
  readonly commit: (ack: PublishAckInput) => DurableStreamMetadata
}

export type DurableAppendPlan =
  | DurableAppendDuplicatePlan
  | DurableAppendMetadataOnlyPlan
  | DurableAppendPublishPlan

const makeBatchMessage = (
  bytes: Uint8Array,
  seq: number,
  byteOffset: number,
): DurableBatchMessage => ({
  offset: makeMshOffset(seq, byteOffset),
  byteLength: bytes.length,
  body: bytes,
})

const makeBatchMessages = (
  messages: ReadonlyArray<Uint8Array>,
  startSeq: number,
  startByteOffset: number,
): ReadonlyArray<DurableBatchMessage> => {
  const out: DurableBatchMessage[] = []
  let seq = startSeq
  let byteOffset = startByteOffset
  for (const bytes of messages) {
    out.push(makeBatchMessage(bytes, seq, byteOffset))
    seq += 1
    byteOffset += bytes.length
  }
  return out
}

const appendProducerEcho = (
  producer: DurableAppendInput["producer"],
): Pick<DurableAppendResult, "producerEpoch" | "producerSeq"> =>
  producer
    ? { producerEpoch: producer.epoch, producerSeq: producer.seq }
    : {}

const makeMsgID = (metadata: DurableStreamMetadata, input: DurableAppendInput): string => {
  const stream = encodeURIComponent(input.streamId as string)
  if (input.producer) {
    return `lnk.${stream}.producer.${encodeURIComponent(input.producer.producerId as string)}.${input.producer.epoch}.${input.producer.seq}`
  }
  return `lnk.${stream}.seq.${metadata.nextSeq}.bytes.${metadata.nextByteOffset}.closed.${input.streamClosed === true ? "1" : "0"}`
}

export const planAppend = (
  metadata: DurableStreamMetadata,
  input: DurableAppendInput,
): Effect.Effect<
  DurableAppendPlan,
  | InvalidPayloadError
  | StaleEpochError
  | SequenceGapError
  | StreamClosedError
  | StreamConfigMismatchError
> =>
  Effect.gen(function* () {
    if (input.contentType !== undefined && !sameContentType(metadata.contentType, input.contentType)) {
      return yield* new StreamConfigMismatchError({
        streamId: input.streamId,
        expectedContentType: metadata.contentType as string,
        receivedContentType: input.contentType as string,
      })
    }

    if (input.producer) {
      const high = metadata.producers[producerKey(input.producer.producerId)]
      if (high) {
        if ((input.producer.epoch as number) < (high.epoch as number)) {
          return yield* new StaleEpochError({
            streamId: input.streamId,
            producerId: input.producer.producerId as string,
            ourEpoch: input.producer.epoch as number,
            serverEpoch: high.epoch as number,
          })
        }
        if ((input.producer.epoch as number) === (high.epoch as number)) {
          if ((input.producer.seq as number) <= (high.lastSeq as number)) {
            return {
              _tag: "Duplicate",
              metadata,
              result: {
                nextOffset: high.lastBatchEndOffset,
                duplicate: true,
                closed: metadata.closed,
                producerEpoch: high.epoch,
                producerSeq: high.lastSeq,
              },
            }
          }
          if ((input.producer.seq as number) > (high.lastSeq as number) + 1) {
            return yield* new SequenceGapError({
              streamId: input.streamId,
              producerId: input.producer.producerId as string,
              expectedSeq: (high.lastSeq as number) + 1,
              receivedSeq: input.producer.seq as number,
            })
          }
        }
        if ((input.producer.epoch as number) > (high.epoch as number) && (input.producer.seq as number) !== 0) {
          return yield* new InvalidPayloadError({
            streamId: input.streamId,
            contentType: metadata.contentType as string,
            reason: "epoch-bump-requires-seq-zero",
          })
        }
      }
    }

    if (input.streamSeq !== undefined && input.streamSeq !== "") {
      if (metadata.lastStreamSeq !== undefined && input.streamSeq <= metadata.lastStreamSeq) {
        return yield* new SequenceGapError({
          streamId: input.streamId,
          producerId: "stream-seq",
          expectedSeq: 0,
          receivedSeq: 0,
        })
      }
    }

    if (input.messages.length === 0) {
      if (input.streamClosed === true) {
        const tail = metadata.lastOffset ?? makeMshOffset(0, 0)
        if (metadata.closed) {
          return {
            _tag: "Duplicate",
            metadata,
            result: {
              nextOffset: tail,
              duplicate: true,
              closed: true,
              ...appendProducerEcho(input.producer),
            },
          }
        }
        const nextMetadata: DurableStreamMetadata = {
          ...metadata,
          closed: true,
          producers: withProducerState(metadata, input.producer, tail),
          ...(input.streamSeq !== undefined && input.streamSeq !== "" ? { lastStreamSeq: input.streamSeq } : {}),
        }
        return {
          _tag: "MetadataOnly",
          metadata: nextMetadata,
          result: {
            nextOffset: tail,
            duplicate: false,
            closed: true,
            ...appendProducerEcho(input.producer),
          },
        }
      }
      return yield* new InvalidPayloadError({
        streamId: input.streamId,
        contentType: metadata.contentType as string,
        reason: "empty-body-without-stream-closed",
      })
    }

    if (metadata.closed) {
      return yield* new StreamClosedError({
        streamId: input.streamId,
        ...(metadata.lastOffset !== undefined ? { lastOffset: metadata.lastOffset } : {}),
      })
    }

    const batchMessages = makeBatchMessages(input.messages, metadata.nextSeq, metadata.nextByteOffset)
    const last = batchMessages[batchMessages.length - 1]!
    const totalBytes = input.messages.reduce((sum, bytes) => sum + bytes.length, 0)
    const nextSeq = metadata.nextSeq + batchMessages.length
    const nextByteOffset = metadata.nextByteOffset + totalBytes
    const closedAfter = input.streamClosed === true
    const envelope: DurableBatchEnvelope = {
      version: 1,
      streamId: input.streamId,
      contentType: metadata.contentType,
      baseSeq: metadata.nextSeq,
      baseByteOffset: metadata.nextByteOffset,
      messages: batchMessages,
      ...(input.producer
        ? {
            producerId: input.producer.producerId,
            producerEpoch: input.producer.epoch,
            producerSeq: input.producer.seq,
          }
        : {}),
      ...(input.streamSeq !== undefined && input.streamSeq !== "" ? { streamSeq: input.streamSeq } : {}),
      streamClosed: closedAfter,
    }
    const result: DurableAppendResult = {
      nextOffset: last.offset,
      duplicate: false,
      closed: closedAfter,
      ...appendProducerEcho(input.producer),
    }

    return {
      _tag: "Publish",
      result,
      envelope,
      msgID: makeMsgID(metadata, input),
      expectedLastSubjectSequence: metadata.lastSubjectSequence,
      commit: (ack) => ({
        ...metadata,
        closed: closedAfter,
        lastOffset: last.offset,
        nextSeq,
        nextByteOffset,
        lastSubjectSequence: ack.subjectSequence,
        producers: withProducerState(metadata, input.producer, last.offset),
        ...(input.streamSeq !== undefined && input.streamSeq !== "" ? { lastStreamSeq: input.streamSeq } : {}),
      }),
    } satisfies DurableAppendPublishPlan
  })
